/* Security+ SY0-701 Glossary — beginner-friendly definitions.
   Fields: t=term/acronym, f=full expansion ("" for concepts), c=category, d=definition.
   Categories: Core · Crypto · IAM · Network · Threats · Malware · SocEng · Cloud · Data · Ops · IR · GRC · Wireless · Endpoint */
window.GLOSSARY = [
/* ── Core Concepts ── */
{t:"Confidentiality",f:"",c:"Core",d:"Keeping data private so only authorized people can see it."},
{t:"Integrity",f:"",c:"Core",d:"Ensuring data has not been altered or tampered with."},
{t:"Availability",f:"",c:"Core",d:"Ensuring systems and data are accessible when needed."},
{t:"CIA Triad",f:"Confidentiality, Integrity, Availability",c:"Core",d:"The three core goals of all security: keep data private, unaltered, and accessible."},
{t:"Non-repudiation",f:"",c:"Core",d:"Proof that someone performed an action so they cannot later deny it — usually via digital signatures."},
{t:"AAA",f:"Authentication, Authorization, and Accounting",c:"Core",d:"The framework for proving identity, granting permissions, and logging what users do."},
{t:"Authentication",f:"",c:"Core",d:"Proving you are who you claim to be (e.g., a password or fingerprint)."},
{t:"Authorization",f:"",c:"Core",d:"Deciding what an authenticated user is allowed to access or do."},
{t:"Accounting",f:"",c:"Core",d:"Recording and tracking user actions for auditing and accountability."},
{t:"Defense in depth",f:"",c:"Core",d:"Layering multiple security controls so if one fails, others still protect the system."},
{t:"Least privilege",f:"",c:"Core",d:"Giving users only the minimum access they need to do their job."},
{t:"Separation of duties",f:"",c:"Core",d:"Splitting a critical task between people so no single person can abuse it."},
{t:"Job rotation",f:"",c:"Core",d:"Moving staff between roles to detect fraud and reduce dependence on one person."},
{t:"Mandatory vacation",f:"",c:"Core",d:"Requiring time off so hidden fraud surfaces while someone else covers the role."},
{t:"Need to know",f:"",c:"Core",d:"Limiting access to information to only those who require it for a task."},
{t:"Implicit deny",f:"",c:"Core",d:"A default rule that blocks anything not explicitly allowed."},
{t:"Zero Trust",f:"",c:"Core",d:"A model that trusts nothing by default and verifies every request, inside or outside the network."},
{t:"Control plane",f:"",c:"Core",d:"In Zero Trust, the part that makes and manages access decisions."},
{t:"Data plane",f:"",c:"Core",d:"In Zero Trust, the part that actually enforces and carries out access decisions."},
{t:"Gap analysis",f:"",c:"Core",d:"Comparing current security to a desired standard to find what is missing."},
{t:"Preventive control",f:"",c:"Core",d:"A control that stops an incident before it happens, like a lock or firewall."},
{t:"Detective control",f:"",c:"Core",d:"A control that identifies an incident after it occurs, like CCTV or logs."},
{t:"Corrective control",f:"",c:"Core",d:"A control that fixes or restores systems after an incident, like a backup."},
{t:"Deterrent control",f:"",c:"Core",d:"A control that discourages an attacker, like a warning sign."},
{t:"Compensating control",f:"",c:"Core",d:"An alternative control used when the preferred control is not possible."},
{t:"Directive control",f:"",c:"Core",d:"A control that instructs behavior, like a policy or procedure."},
{t:"Technical control",f:"",c:"Core",d:"A control enforced by technology, like encryption or access lists."},
{t:"Managerial control",f:"",c:"Core",d:"A control implemented through policy and management decisions, like risk assessments."},
{t:"Operational control",f:"",c:"Core",d:"A control carried out by people in day-to-day operations, like security training."},
{t:"Physical control",f:"",c:"Core",d:"A tangible control like fences, locks, guards, or badges."},

/* ── Cryptography & PKI ── */
{t:"Encryption",f:"",c:"Crypto",d:"Scrambling data so only someone with the key can read it."},
{t:"Plaintext",f:"",c:"Crypto",d:"Readable data before it is encrypted."},
{t:"Ciphertext",f:"",c:"Crypto",d:"The scrambled, unreadable output of encryption."},
{t:"Symmetric encryption",f:"",c:"Crypto",d:"Encryption that uses the same secret key to both encrypt and decrypt; fast but the key must be shared safely."},
{t:"Asymmetric encryption",f:"",c:"Crypto",d:"Encryption using a public/private key pair; one key encrypts and the other decrypts."},
{t:"Public key",f:"",c:"Crypto",d:"The freely shared key in a key pair, used to encrypt to you or verify your signature."},
{t:"Private key",f:"",c:"Crypto",d:"The secret key in a key pair that you must protect; used to decrypt or sign."},
{t:"Hashing",f:"",c:"Crypto",d:"A one-way function that turns data into a fixed-length fingerprint to verify integrity."},
{t:"Salt",f:"",c:"Crypto",d:"Random data added to a password before hashing so identical passwords hash differently."},
{t:"Pepper",f:"",c:"Crypto",d:"A secret value added to a password hash and stored separately from the database."},
{t:"Key stretching",f:"",c:"Crypto",d:"Deliberately slowing down password hashing (e.g., PBKDF2, bcrypt) to resist brute force."},
{t:"Digital signature",f:"",c:"Crypto",d:"Data signed with a private key to prove who sent it and that it was not changed."},
{t:"AES",f:"Advanced Encryption Standard",c:"Crypto",d:"The modern, strong symmetric encryption standard used almost everywhere today."},
{t:"DES",f:"Data Encryption Standard",c:"Crypto",d:"An old, now-insecure symmetric cipher with a too-short 56-bit key; replaced by AES."},
{t:"3DES",f:"Triple DES",c:"Crypto",d:"DES applied three times for more strength; deprecated in favor of AES."},
{t:"RSA",f:"Rivest-Shamir-Adleman",c:"Crypto",d:"A widely used asymmetric algorithm for encryption and digital signatures."},
{t:"ECC",f:"Elliptic Curve Cryptography",c:"Crypto",d:"Asymmetric cryptography that provides strong security with smaller, faster keys — good for mobile."},
{t:"DSA",f:"Digital Signature Algorithm",c:"Crypto",d:"An algorithm used specifically to create digital signatures."},
{t:"SHA",f:"Secure Hash Algorithm",c:"Crypto",d:"A family of hashing algorithms; SHA-256 is the common secure choice today."},
{t:"MD5",f:"Message Digest 5",c:"Crypto",d:"An old hashing algorithm now considered broken due to collisions; avoid for security."},
{t:"RIPEMD",f:"RACE Integrity Primitives Evaluation Message Digest",c:"Crypto",d:"A hashing algorithm family, an alternative to SHA."},
{t:"HMAC",f:"Hash-based Message Authentication Code",c:"Crypto",d:"Combines a hash with a secret key to verify both integrity and authenticity of a message."},
{t:"Digital certificate",f:"",c:"Crypto",d:"An electronic document that binds a public key to an identity, signed by a trusted authority."},
{t:"CA",f:"Certificate Authority",c:"Crypto",d:"A trusted organization that issues and signs digital certificates."},
{t:"Root CA",f:"Root Certificate Authority",c:"Crypto",d:"The top, most-trusted certificate authority whose key anchors the whole chain of trust."},
{t:"Intermediate CA",f:"Intermediate Certificate Authority",c:"Crypto",d:"A CA that sits below the root and issues certificates, protecting the root from exposure."},
{t:"Chain of trust",f:"",c:"Crypto",d:"The linked path of certificates from a trusted root down to a server's certificate."},
{t:"Self-signed certificate",f:"",c:"Crypto",d:"A certificate signed by its own creator instead of a trusted CA; fine for testing, not public trust."},
{t:"Wildcard certificate",f:"",c:"Crypto",d:"A certificate that secures a domain and all of its subdomains (e.g., *.example.com)."},
{t:"Certificate pinning",f:"",c:"Crypto",d:"Hard-coding an expected certificate or key so an app rejects fraudulent ones."},
{t:"CSR",f:"Certificate Signing Request",c:"Crypto",d:"A request containing your public key and details, sent to a CA to get a certificate issued."},
{t:"CRL",f:"Certificate Revocation List",c:"Crypto",d:"A published list of certificates that have been revoked and should no longer be trusted."},
{t:"OCSP",f:"Online Certificate Status Protocol",c:"Crypto",d:"A faster way to check in real time whether a single certificate is still valid."},
{t:"Key escrow",f:"",c:"Crypto",d:"Storing a copy of encryption keys with a trusted third party for recovery."},
{t:"PKI",f:"Public Key Infrastructure",c:"Crypto",d:"The whole system of CAs, certificates, and keys that makes public-key encryption trustworthy."},
{t:"PFS",f:"Perfect Forward Secrecy",c:"Crypto",d:"Using fresh temporary keys per session so a stolen long-term key can't decrypt past traffic."},
{t:"Ephemeral key",f:"",c:"Crypto",d:"A temporary key used for a single session and then discarded."},
{t:"Session key",f:"",c:"Crypto",d:"A short-lived symmetric key used to encrypt one communication session."},
{t:"Block cipher",f:"",c:"Crypto",d:"A cipher that encrypts data in fixed-size chunks (blocks), like AES."},
{t:"Stream cipher",f:"",c:"Crypto",d:"A cipher that encrypts data one bit or byte at a time."},
{t:"Nonce",f:"Number used once",c:"Crypto",d:"A random or unique value used once to prevent replay attacks."},
{t:"IV",f:"Initialization Vector",c:"Crypto",d:"A random starting value that makes encrypting the same data produce different ciphertext."},
{t:"Collision",f:"",c:"Crypto",d:"When two different inputs produce the same hash — a sign a hash algorithm is weak."},
{t:"Birthday attack",f:"",c:"Crypto",d:"An attack that exploits hash collisions using probability (the birthday paradox)."},
{t:"Steganography",f:"",c:"Crypto",d:"Hiding data inside another file, like concealing a message in an image."},
{t:"Obfuscation",f:"",c:"Crypto",d:"Making data or code hard to understand to slow down attackers."},
{t:"Tokenization",f:"",c:"Crypto",d:"Replacing sensitive data with a meaningless token mapped back in a secure vault."},
{t:"Data masking",f:"",c:"Crypto",d:"Hiding parts of data, like showing only the last four digits of a card number."},
{t:"Homomorphic encryption",f:"",c:"Crypto",d:"Encryption that lets you compute on data while it stays encrypted."},
{t:"Diffie-Hellman",f:"",c:"Crypto",d:"A method for two parties to securely agree on a shared secret key over an open channel."},
{t:"Post-quantum cryptography",f:"",c:"Crypto",d:"New algorithms designed to resist future quantum computers that could break today's crypto."},
{t:"Cipher suite",f:"",c:"Crypto",d:"The agreed set of algorithms (key exchange, encryption, hashing) used in a TLS connection."},
{t:"PBKDF2",f:"Password-Based Key Derivation Function 2",c:"Crypto",d:"A key-stretching function that hashes passwords many times to slow attackers."},
{t:"PGP",f:"Pretty Good Privacy",c:"Crypto",d:"Software for encrypting and signing email and files using public-key cryptography."},
{t:"GPG",f:"GNU Privacy Guard",c:"Crypto",d:"A free, open-source implementation of the PGP encryption standard."},
{t:"S/MIME",f:"Secure/Multipurpose Internet Mail Extensions",c:"Crypto",d:"A standard for encrypting and digitally signing email using certificates."},
{t:"KEK",f:"Key Encryption Key",c:"Crypto",d:"A key whose only job is to encrypt other keys for safe storage."},
{t:"HSM",f:"Hardware Security Module",c:"Crypto",d:"A tamper-resistant physical device that generates and stores cryptographic keys securely."},

/* ── Identity & Access ── */
{t:"IAM",f:"Identity and Access Management",c:"IAM",d:"The systems and policies that manage user identities and what they can access."},
{t:"Identity proofing",f:"",c:"IAM",d:"Verifying that a person is who they claim before issuing them credentials."},
{t:"Credential",f:"",c:"IAM",d:"Something used to prove identity, such as a username/password or certificate."},
{t:"MFA",f:"Multi-Factor Authentication",c:"IAM",d:"Requiring two or more different proof types (e.g., password plus phone code) to log in."},
{t:"Biometrics",f:"",c:"IAM",d:"Using physical traits like fingerprints or face scans to authenticate."},
{t:"FAR",f:"False Acceptance Rate",c:"IAM",d:"How often a biometric system wrongly accepts an unauthorized person."},
{t:"FRR",f:"False Rejection Rate",c:"IAM",d:"How often a biometric system wrongly rejects an authorized person."},
{t:"CER",f:"Crossover Error Rate",c:"IAM",d:"The point where false acceptance and false rejection rates are equal; lower is better."},
{t:"Something you know",f:"",c:"IAM",d:"An authentication factor based on knowledge, like a password or PIN."},
{t:"Something you have",f:"",c:"IAM",d:"An authentication factor based on possession, like a token or smart card."},
{t:"Something you are",f:"",c:"IAM",d:"An authentication factor based on a biometric trait, like a fingerprint."},
{t:"Somewhere you are",f:"",c:"IAM",d:"An authentication factor based on location, like GPS or network address."},
{t:"HOTP",f:"HMAC-based One-Time Password",c:"IAM",d:"A one-time code generated from a counter that changes with each use."},
{t:"TOTP",f:"Time-based One-Time Password",c:"IAM",d:"A one-time code that changes every 30–60 seconds based on the current time."},
{t:"SSO",f:"Single Sign-On",c:"IAM",d:"Logging in once to gain access to many systems without re-entering credentials."},
{t:"Federation",f:"",c:"IAM",d:"Trusting identities from another organization so users can log in across domains."},
{t:"SAML",f:"Security Assertion Markup Language",c:"IAM",d:"An XML standard that lets identity providers pass login info for single sign-on."},
{t:"OAuth",f:"Open Authorization",c:"IAM",d:"A standard that lets apps access resources on your behalf without sharing your password."},
{t:"OpenID Connect",f:"",c:"IAM",d:"An identity layer built on OAuth that confirms who the user is for single sign-on."},
{t:"Kerberos",f:"",c:"IAM",d:"A network authentication protocol that uses tickets and a key distribution center; common in Windows domains."},
{t:"KDC",f:"Key Distribution Center",c:"IAM",d:"The Kerberos server that issues authentication tickets to users and services."},
{t:"TGT",f:"Ticket Granting Ticket",c:"IAM",d:"A Kerberos ticket that proves you logged in and lets you request access to services."},
{t:"LDAP",f:"Lightweight Directory Access Protocol",c:"IAM",d:"A protocol for querying and managing a directory of users and resources."},
{t:"RADIUS",f:"Remote Authentication Dial-In User Service",c:"IAM",d:"A protocol that centrally authenticates remote and wireless users."},
{t:"TACACS+",f:"Terminal Access Controller Access-Control System Plus",c:"IAM",d:"A Cisco AAA protocol that encrypts the full session and separates authentication from authorization."},
{t:"PAP",f:"Password Authentication Protocol",c:"IAM",d:"An old authentication method that sends passwords in cleartext; insecure."},
{t:"CHAP",f:"Challenge-Handshake Authentication Protocol",c:"IAM",d:"An authentication method that verifies identity with a challenge without sending the password."},
{t:"EAP",f:"Extensible Authentication Protocol",c:"IAM",d:"A flexible framework supporting many authentication methods, often used in Wi-Fi."},
{t:"802.1X",f:"",c:"IAM",d:"A standard for port-based network access control that authenticates devices before granting access."},
{t:"PAM (privileged access)",f:"Privileged Access Management",c:"IAM",d:"Tools and policies that secure, monitor, and limit powerful admin accounts."},
{t:"PAM (auth modules)",f:"Pluggable Authentication Modules",c:"IAM",d:"A Linux framework that lets programs use shared authentication methods."},
{t:"Just-in-time permissions",f:"",c:"IAM",d:"Granting elevated access only for the moment it is needed, then revoking it."},
{t:"Passwordless",f:"",c:"IAM",d:"Authentication without a password, using methods like biometrics or hardware keys."},
{t:"Provisioning",f:"",c:"IAM",d:"Creating and setting up user accounts and their access."},
{t:"Deprovisioning",f:"",c:"IAM",d:"Disabling or removing accounts and access when no longer needed (e.g., after offboarding)."},
{t:"DAC",f:"Discretionary Access Control",c:"IAM",d:"An access model where the resource owner decides who gets access."},
{t:"MAC (access control)",f:"Mandatory Access Control",c:"IAM",d:"An access model where the system enforces access using labels and clearances; common in military settings."},
{t:"RBAC",f:"Role-Based Access Control",c:"IAM",d:"An access model that grants permissions based on a user's job role."},
{t:"ABAC",f:"Attribute-Based Access Control",c:"IAM",d:"An access model that decides access from attributes like department, time, or location."},
{t:"Rule-based access control",f:"",c:"IAM",d:"Access decided by predefined rules, such as a firewall's access control list."},
{t:"ACL",f:"Access Control List",c:"IAM",d:"A list of rules specifying who or what is allowed access to a resource."},
{t:"Conditional access",f:"",c:"IAM",d:"Allowing or blocking access based on conditions like device health, location, or risk."},
{t:"Attestation",f:"",c:"IAM",d:"A device or system proving its identity and integrity to be trusted."},
{t:"PIV",f:"Personal Identity Verification",c:"IAM",d:"A smart-card credential standard used by US federal employees for secure access."},

/* ── Network Security ── */
{t:"Firewall",f:"",c:"Network",d:"A device or software that filters network traffic based on a set of rules."},
{t:"Stateful firewall",f:"",c:"Network",d:"A firewall that tracks active connections and allows return traffic for them."},
{t:"WAF",f:"Web Application Firewall",c:"Network",d:"A firewall that protects web apps by filtering malicious HTTP requests like SQL injection."},
{t:"NGFW",f:"Next-Generation Firewall",c:"Network",d:"An advanced firewall that adds app awareness, intrusion prevention, and deep inspection."},
{t:"UTM",f:"Unified Threat Management",c:"Network",d:"An all-in-one appliance combining firewall, antivirus, IPS, filtering, and more."},
{t:"Proxy server",f:"",c:"Network",d:"An intermediary that forwards, filters, and can cache requests between clients and servers."},
{t:"Forward proxy",f:"",c:"Network",d:"A proxy that sits in front of clients to control their outbound access."},
{t:"Reverse proxy",f:"",c:"Network",d:"A proxy that sits in front of servers to protect and load-balance them."},
{t:"Load balancer",f:"",c:"Network",d:"A device that spreads traffic across multiple servers for performance and resilience."},
{t:"Jump server",f:"",c:"Network",d:"A hardened host used as a controlled gateway to manage systems in a secure zone."},
{t:"VPN",f:"Virtual Private Network",c:"Network",d:"An encrypted tunnel that lets you securely connect over an untrusted network like the internet."},
{t:"Site-to-site VPN",f:"",c:"Network",d:"A permanent VPN that links two whole networks, like two office locations."},
{t:"Remote access VPN",f:"",c:"Network",d:"A VPN that lets individual users connect securely to a network from anywhere."},
{t:"Split tunneling",f:"",c:"Network",d:"A VPN setup where only some traffic goes through the tunnel and the rest goes direct."},
{t:"Full tunnel",f:"",c:"Network",d:"A VPN setup where all of a device's traffic is routed through the secure tunnel."},
{t:"IPSec",f:"Internet Protocol Security",c:"Network",d:"A protocol suite that encrypts and authenticates IP traffic, often for VPNs."},
{t:"AH",f:"Authentication Header",c:"Network",d:"An IPsec component that provides integrity and authentication but not encryption."},
{t:"ESP",f:"Encapsulating Security Payload",c:"Network",d:"An IPsec component that provides encryption plus integrity for the data."},
{t:"IKE",f:"Internet Key Exchange",c:"Network",d:"The IPsec protocol that negotiates keys and sets up the secure tunnel."},
{t:"TLS",f:"Transport Layer Security",c:"Network",d:"The standard protocol that encrypts internet traffic like HTTPS; the successor to SSL."},
{t:"SSL",f:"Secure Sockets Layer",c:"Network",d:"The old, now-deprecated protocol for encrypting web traffic, replaced by TLS."},
{t:"IDS",f:"Intrusion Detection System",c:"Network",d:"A system that watches traffic and alerts on suspicious activity but does not block it."},
{t:"IPS",f:"Intrusion Prevention System",c:"Network",d:"An inline system that detects and actively blocks malicious traffic."},
{t:"Signature-based detection",f:"",c:"Network",d:"Detecting threats by matching known patterns; misses brand-new attacks."},
{t:"Anomaly-based detection",f:"",c:"Network",d:"Detecting threats by spotting deviations from normal behavior; can catch unknown attacks."},
{t:"Network segmentation",f:"",c:"Network",d:"Dividing a network into separate zones to limit how far an attacker can move."},
{t:"Microsegmentation",f:"",c:"Network",d:"Very fine-grained segmentation, often per-workload, to stop lateral movement."},
{t:"Screened subnet",f:"",c:"Network",d:"A buffer network (formerly called a DMZ) that hosts public services apart from the internal LAN."},
{t:"DMZ",f:"Demilitarized Zone",c:"Network",d:"An older name for a screened subnet exposing public-facing servers safely."},
{t:"East-west traffic",f:"",c:"Network",d:"Network traffic moving between servers inside the same data center."},
{t:"North-south traffic",f:"",c:"Network",d:"Network traffic moving in and out of the data center to clients."},
{t:"NAT",f:"Network Address Translation",c:"Network",d:"Translating private internal IP addresses to a public one to reach the internet."},
{t:"PAT",f:"Port Address Translation",c:"Network",d:"A form of NAT that maps many private addresses to one public IP using port numbers."},
{t:"SDN",f:"Software-Defined Networking",c:"Network",d:"Managing the network through software/controllers rather than configuring each device by hand."},
{t:"SD-WAN",f:"Software-Defined Wide Area Network",c:"Network",d:"Using software to intelligently route traffic across multiple WAN links."},
{t:"SASE",f:"Secure Access Service Edge",c:"Network",d:"A cloud model that combines networking and security services delivered at the edge."},
{t:"ZTNA",f:"Zero Trust Network Access",c:"Network",d:"Technology that grants application access per-request after verifying identity and context."},
{t:"Content filter",f:"",c:"Network",d:"A control that blocks access to disallowed websites or content categories."},
{t:"DNS sinkhole",f:"",c:"Network",d:"Redirecting requests for malicious domains to a safe dead-end address."},
{t:"Port security",f:"",c:"Network",d:"A switch feature that limits which devices can connect to a physical port."},
{t:"Port mirroring",f:"Switched Port Analyzer (SPAN)",c:"Network",d:"Copying traffic from switch ports to a monitoring tool for analysis."},
{t:"Network tap",f:"",c:"Network",d:"A hardware device that copies network traffic for monitoring without disrupting it."},
{t:"Out-of-band management",f:"",c:"Network",d:"Managing devices over a separate channel so it works even if the main network is down."},
{t:"Air gap",f:"",c:"Network",d:"Physically isolating a system from other networks for maximum protection."},
{t:"Honeypot",f:"",c:"Network",d:"A decoy system set up to lure attackers and study their behavior."},
{t:"Honeynet",f:"",c:"Network",d:"A whole network of honeypots used to observe attacks at scale."},
{t:"Honeytoken",f:"",c:"Network",d:"Fake data planted to trigger an alert when an intruder accesses or uses it."},
{t:"OSI model",f:"Open Systems Interconnection model",c:"Network",d:"A 7-layer framework (Physical to Application) describing how network communication works."},
{t:"Three-way handshake",f:"",c:"Network",d:"The SYN, SYN-ACK, ACK exchange that establishes a TCP connection."},
{t:"ARP",f:"Address Resolution Protocol",c:"Network",d:"A protocol that maps IP addresses to hardware (MAC) addresses on a local network."},
{t:"DNS",f:"Domain Name System",c:"Network",d:"The internet service that translates human names like example.com into IP addresses."},
{t:"DNSSEC",f:"Domain Name System Security Extensions",c:"Network",d:"Add-ons that digitally sign DNS records so responses can be trusted as authentic."},
{t:"DHCP",f:"Dynamic Host Configuration Protocol",c:"Network",d:"A protocol that automatically assigns IP addresses to devices on a network."},
{t:"ICMP",f:"Internet Control Message Protocol",c:"Network",d:"A protocol for network diagnostics and error messages, used by tools like ping."},
{t:"VLAN",f:"Virtual Local Area Network",c:"Network",d:"A logical grouping of devices into separate networks on the same physical switch."},
{t:"NAC",f:"Network Access Control",c:"Network",d:"Technology that checks a device's identity and health before letting it on the network."},
{t:"MAC (media access)",f:"Media Access Control address",c:"Network",d:"A unique hardware address burned into a network interface card."},
{t:"MAC (message auth)",f:"Message Authentication Code",c:"Network",d:"A short tag that verifies a message's integrity and authenticity using a key."},

/* ── Threats & Attacks ── */
{t:"Threat actor",f:"",c:"Threats",d:"Any person or group that carries out or intends a malicious action."},
{t:"Nation-state actor",f:"",c:"Threats",d:"A government-backed, well-funded attacker, often behind advanced persistent threats."},
{t:"APT",f:"Advanced Persistent Threat",c:"Threats",d:"A sophisticated attacker that quietly maintains long-term access to a target."},
{t:"Hacktivist",f:"",c:"Threats",d:"An attacker motivated by a political or social cause rather than money."},
{t:"Insider threat",f:"",c:"Threats",d:"A risk from someone inside the organization, whether malicious or careless."},
{t:"Unskilled attacker",f:"Script kiddie",c:"Threats",d:"A low-skill attacker who relies on prebuilt tools and exploits."},
{t:"Shadow IT",f:"",c:"Threats",d:"Hardware or software used without IT's approval, creating unmanaged risk."},
{t:"Threat vector",f:"",c:"Threats",d:"The path or method an attacker uses to reach and compromise a target."},
{t:"Attack surface",f:"",c:"Threats",d:"The total set of points where an attacker could try to get in."},
{t:"Vulnerability",f:"",c:"Threats",d:"A weakness in a system that could be exploited by a threat."},
{t:"Exploit",f:"",c:"Threats",d:"Code or a technique that takes advantage of a vulnerability."},
{t:"Zero-day",f:"",c:"Threats",d:"A vulnerability that is exploited before a patch or signature exists."},
{t:"Supply chain attack",f:"",c:"Threats",d:"Compromising a trusted vendor or component to reach the real target."},
{t:"Watering hole attack",f:"",c:"Threats",d:"Compromising a website the target group is known to visit, to infect them."},
{t:"Lateral movement",f:"",c:"Threats",d:"An attacker moving from one compromised system to others inside the network."},
{t:"Privilege escalation",f:"",c:"Threats",d:"Gaining higher permissions than were originally granted."},
{t:"CVE",f:"Common Vulnerabilities and Exposures",c:"Threats",d:"A public catalog that gives each known vulnerability a unique ID."},
{t:"CVSS",f:"Common Vulnerability Scoring System",c:"Threats",d:"A 0–10 score rating how severe a vulnerability is."},
{t:"IoC",f:"Indicator of Compromise",c:"Threats",d:"Evidence that a system may have been breached, like a malicious IP or file hash."},
{t:"TTP",f:"Tactics, Techniques, and Procedures",c:"Threats",d:"The patterns of behavior that describe how a specific attacker operates."},
{t:"OSINT",f:"Open-Source Intelligence",c:"Threats",d:"Gathering intelligence from publicly available sources."},
{t:"STIX",f:"Structured Threat Information eXpression",c:"Threats",d:"A standard language for describing and sharing cyber threat information."},
{t:"TAXII",f:"Trusted Automated eXchange of Indicator Information",c:"Threats",d:"A protocol for automatically sharing threat intelligence between systems."},
{t:"DoS",f:"Denial of Service",c:"Threats",d:"An attack that overwhelms a system so legitimate users cannot use it."},
{t:"DDoS",f:"Distributed Denial of Service",c:"Threats",d:"A denial-of-service attack launched from many machines at once, often a botnet."},
{t:"On-path attack",f:"Man-in-the-Middle (MITM)",c:"Threats",d:"An attacker secretly intercepting or altering traffic between two parties."},
{t:"ARP poisoning",f:"",c:"Threats",d:"Faking ARP messages to redirect a network's traffic to the attacker."},
{t:"DNS poisoning",f:"DNS spoofing",c:"Threats",d:"Corrupting DNS data so users are sent to a malicious site."},
{t:"VLAN hopping",f:"",c:"Threats",d:"An attack that lets traffic reach a VLAN it should not be able to access."},
{t:"Replay attack",f:"",c:"Threats",d:"Capturing valid data and re-sending it later to impersonate a user."},
{t:"SQLi",f:"SQL Injection",c:"Threats",d:"Inserting malicious database commands through input fields to read or change data."},
{t:"XSS",f:"Cross-Site Scripting",c:"Threats",d:"Injecting malicious scripts that run in another user's browser."},
{t:"CSRF",f:"Cross-Site Request Forgery",c:"Threats",d:"Tricking a logged-in user's browser into making an unwanted request."},
{t:"SSRF",f:"Server-Side Request Forgery",c:"Threats",d:"Tricking a server into making requests to systems the attacker can't reach directly."},
{t:"Buffer overflow",f:"",c:"Threats",d:"Writing more data than a memory buffer holds to crash or hijack a program."},
{t:"Race condition",f:"Time-of-check to time-of-use (TOCTOU)",c:"Threats",d:"Exploiting the gap between when a resource is checked and when it is used."},
{t:"Directory traversal",f:"",c:"Threats",d:"Using paths like ../ to access files outside the intended folder."},
{t:"Session hijacking",f:"",c:"Threats",d:"Stealing a user's session token to take over their logged-in session."},
{t:"Brute-force attack",f:"",c:"Threats",d:"Trying many passwords or keys until the right one is found."},
{t:"Dictionary attack",f:"",c:"Threats",d:"Trying passwords from a list of common words."},
{t:"Password spraying",f:"",c:"Threats",d:"Trying a few common passwords across many accounts to avoid lockouts."},
{t:"Credential stuffing",f:"",c:"Threats",d:"Reusing stolen username/password pairs from one breach against other sites."},
{t:"Rainbow table",f:"",c:"Threats",d:"A precomputed table of hashes used to crack passwords quickly; salting defeats it."},
{t:"Pass the hash",f:"",c:"Threats",d:"Using a stolen password hash to authenticate without knowing the actual password."},
{t:"Downgrade attack",f:"",c:"Threats",d:"Forcing a connection to use a weaker, older protocol that is easier to break."},

/* ── Malware ── */
{t:"Malware",f:"Malicious software",c:"Malware",d:"Any software written to harm, exploit, or gain unauthorized access to systems."},
{t:"Virus",f:"",c:"Malware",d:"Malware that attaches to a file and spreads when that file is run."},
{t:"Worm",f:"",c:"Malware",d:"Malware that self-replicates across networks with no user action."},
{t:"Trojan",f:"Trojan horse",c:"Malware",d:"Malware disguised as legitimate software to trick you into running it."},
{t:"RAT",f:"Remote Access Trojan",c:"Malware",d:"A trojan that gives an attacker full remote control of the infected machine."},
{t:"Ransomware",f:"",c:"Malware",d:"Malware that encrypts your files and demands payment for the key."},
{t:"Spyware",f:"",c:"Malware",d:"Malware that secretly collects information about you and your activity."},
{t:"Adware",f:"",c:"Malware",d:"Software that displays unwanted ads, sometimes bundled with spyware."},
{t:"Rootkit",f:"",c:"Malware",d:"Malware that hides deep in the system, often at kernel level, to evade detection."},
{t:"Bootkit",f:"",c:"Malware",d:"A rootkit that infects the boot process so it loads before the operating system."},
{t:"Keylogger",f:"",c:"Malware",d:"Software or hardware that secretly records everything you type."},
{t:"Logic bomb",f:"",c:"Malware",d:"Malicious code that triggers when a specific condition or date is met."},
{t:"Fileless malware",f:"",c:"Malware",d:"Malware that runs in memory using built-in tools, leaving little trace on disk."},
{t:"Backdoor",f:"",c:"Malware",d:"A hidden way to bypass normal authentication and access a system."},
{t:"Botnet",f:"",c:"Malware",d:"A network of infected machines controlled by an attacker, often used for DDoS."},
{t:"C2",f:"Command and Control",c:"Malware",d:"The server infrastructure an attacker uses to control infected machines."},
{t:"PUP",f:"Potentially Unwanted Program",c:"Malware",d:"Software that is not strictly malware but is unwanted, like bundled toolbars."},

/* ── Social Engineering ── */
{t:"Social engineering",f:"",c:"SocEng",d:"Manipulating people into revealing information or taking unsafe actions."},
{t:"Phishing",f:"",c:"SocEng",d:"Fraudulent emails that trick people into giving up information or clicking malicious links."},
{t:"Spear phishing",f:"",c:"SocEng",d:"A phishing attack tailored to a specific person or organization."},
{t:"Whaling",f:"",c:"SocEng",d:"A phishing attack that targets high-value executives."},
{t:"Vishing",f:"Voice phishing",c:"SocEng",d:"Social engineering carried out over phone calls."},
{t:"Smishing",f:"SMS phishing",c:"SocEng",d:"Social engineering carried out through text messages."},
{t:"Pharming",f:"",c:"SocEng",d:"Redirecting users from a legitimate site to a fake one, often via DNS poisoning."},
{t:"Pretexting",f:"",c:"SocEng",d:"Inventing a believable scenario to gain a victim's trust and information."},
{t:"Baiting",f:"",c:"SocEng",d:"Luring victims with something enticing, like a dropped malware-laden USB drive."},
{t:"Tailgating",f:"",c:"SocEng",d:"Following an authorized person through a secure door without credentials."},
{t:"Piggybacking",f:"",c:"SocEng",d:"Entering a secure area with an authorized person's knowing consent."},
{t:"Shoulder surfing",f:"",c:"SocEng",d:"Watching over someone's shoulder to steal passwords or data."},
{t:"Dumpster diving",f:"",c:"SocEng",d:"Searching trash for sensitive information that wasn't properly destroyed."},
{t:"BEC",f:"Business Email Compromise",c:"SocEng",d:"Impersonating an executive or vendor by email to trick staff into sending money or data."},
{t:"Typosquatting",f:"",c:"SocEng",d:"Registering misspelled domain names to catch users who mistype a real site."},
{t:"Impersonation",f:"",c:"SocEng",d:"Pretending to be someone trusted to manipulate a victim."},
{t:"Influence campaign",f:"",c:"SocEng",d:"Coordinated use of misinformation to shape opinions or behavior."},

/* ── Architecture & Cloud ── */
{t:"CSP",f:"Cloud Service Provider",c:"Cloud",d:"A company that delivers computing resources over the internet, like AWS or Azure."},
{t:"IaaS",f:"Infrastructure as a Service",c:"Cloud",d:"Cloud model where you rent infrastructure and manage the OS and apps yourself."},
{t:"PaaS",f:"Platform as a Service",c:"Cloud",d:"Cloud model where the provider manages the platform and you just deploy your code."},
{t:"SaaS",f:"Software as a Service",c:"Cloud",d:"Cloud model where you simply use an application over the internet."},
{t:"Shared responsibility model",f:"",c:"Cloud",d:"The split of security duties between the cloud provider and the customer."},
{t:"Hybrid cloud",f:"",c:"Cloud",d:"A mix of private and public cloud resources working together."},
{t:"Virtualization",f:"",c:"Cloud",d:"Running multiple virtual machines on one physical computer."},
{t:"Hypervisor",f:"",c:"Cloud",d:"Software that creates and runs virtual machines."},
{t:"Type 1 hypervisor",f:"Bare-metal hypervisor",c:"Cloud",d:"A hypervisor that runs directly on hardware, used in data centers."},
{t:"Type 2 hypervisor",f:"Hosted hypervisor",c:"Cloud",d:"A hypervisor that runs on top of a normal operating system."},
{t:"VM escape",f:"Virtual Machine escape",c:"Cloud",d:"Breaking out of a virtual machine to attack the host or other VMs."},
{t:"VM sprawl",f:"",c:"Cloud",d:"Uncontrolled growth of unmanaged virtual machines, increasing risk."},
{t:"Containerization",f:"",c:"Cloud",d:"Packaging an app with its dependencies into a lightweight, portable container."},
{t:"Serverless",f:"",c:"Cloud",d:"Running code on demand without managing the underlying servers."},
{t:"IaC",f:"Infrastructure as Code",c:"Cloud",d:"Defining and provisioning infrastructure through code for consistency and automation."},
{t:"CASB",f:"Cloud Access Security Broker",c:"Cloud",d:"A security checkpoint between users and cloud services that enforces policy."},
{t:"SWG",f:"Secure Web Gateway",c:"Cloud",d:"A control that filters and inspects web traffic to block threats and enforce policy."},
{t:"CDN",f:"Content Delivery Network",c:"Cloud",d:"A network of distributed servers that delivers content faster and absorbs traffic spikes."},
{t:"Edge computing",f:"",c:"Cloud",d:"Processing data near where it is generated instead of in a central cloud."},
{t:"High availability",f:"",c:"Cloud",d:"Designing systems to stay running with minimal downtime."},
{t:"Redundancy",f:"",c:"Cloud",d:"Having backup components so a single failure doesn't cause an outage."},
{t:"Failover",f:"",c:"Cloud",d:"Automatically switching to a standby system when the primary one fails."},
{t:"RAID",f:"Redundant Array of Independent Disks",c:"Cloud",d:"Combining multiple drives for performance and/or fault tolerance."},

/* ── Data Protection ── */
{t:"Data at rest",f:"",c:"Data",d:"Data stored on a disk or device, protected by encryption like full disk encryption."},
{t:"Data in transit",f:"",c:"Data",d:"Data moving across a network, protected by encryption like TLS."},
{t:"Data in use",f:"",c:"Data",d:"Data actively being processed in memory."},
{t:"Data classification",f:"",c:"Data",d:"Labeling data by sensitivity (e.g., public, confidential) to apply the right controls."},
{t:"DLP",f:"Data Loss Prevention",c:"Data",d:"Technology that detects and blocks sensitive data from leaving the organization."},
{t:"Data sovereignty",f:"",c:"Data",d:"The idea that data is subject to the laws of the country where it is stored."},
{t:"Data owner",f:"",c:"Data",d:"The person accountable for a set of data and its classification."},
{t:"Data controller",f:"",c:"Data",d:"The party that decides why and how personal data is processed."},
{t:"Data processor",f:"",c:"Data",d:"The party that handles personal data on behalf of the controller."},
{t:"Data custodian",f:"",c:"Data",d:"The person responsible for the technical storage and protection of data."},
{t:"Data steward",f:"",c:"Data",d:"The person responsible for data quality and proper use."},
{t:"Anonymization",f:"",c:"Data",d:"Permanently removing identifying details so data can't be traced to a person."},
{t:"Pseudonymization",f:"",c:"Data",d:"Replacing identifying fields with pseudonyms that can be reversed with a key."},
{t:"PII",f:"Personally Identifiable Information",c:"Data",d:"Data that can identify a specific person, like a name or Social Security number."},
{t:"PHI",f:"Protected Health Information",c:"Data",d:"Health data protected by law such as HIPAA."},
{t:"FDE",f:"Full Disk Encryption",c:"Data",d:"Encrypting an entire drive so data is unreadable if the device is lost or stolen."},
{t:"SED",f:"Self-Encrypting Drive",c:"Data",d:"A drive that automatically encrypts all data using built-in hardware."},

/* ── Operations & Monitoring ── */
{t:"SIEM",f:"Security Information and Event Management",c:"Ops",d:"A platform that collects and correlates logs from across the network to detect and alert on threats."},
{t:"SOAR",f:"Security Orchestration, Automation, and Response",c:"Ops",d:"Tools that automate security workflows and incident response playbooks."},
{t:"Syslog",f:"",c:"Ops",d:"A standard protocol for sending log messages to a central server."},
{t:"NetFlow",f:"",c:"Ops",d:"A protocol that records metadata about network traffic — who talked to whom."},
{t:"Packet capture",f:"PCAP",c:"Ops",d:"Recording full network traffic for detailed analysis."},
{t:"EDR",f:"Endpoint Detection and Response",c:"Ops",d:"Software on devices that detects, investigates, and responds to threats."},
{t:"XDR",f:"Extended Detection and Response",c:"Ops",d:"Detection and response that correlates data across endpoints, network, cloud, and email."},
{t:"FIM",f:"File Integrity Monitoring",c:"Ops",d:"Watching critical files for unauthorized changes."},
{t:"Vulnerability scan",f:"",c:"Ops",d:"An automated check that finds known weaknesses in systems."},
{t:"Credentialed scan",f:"",c:"Ops",d:"A vulnerability scan run with login access for a deeper, more accurate view."},
{t:"False positive",f:"",c:"Ops",d:"An alert that flags something as malicious when it is actually benign."},
{t:"False negative",f:"",c:"Ops",d:"A real threat that the system fails to detect."},
{t:"Penetration testing",f:"",c:"Ops",d:"Authorized simulated attacks to find exploitable weaknesses before real attackers do."},
{t:"Black-box testing",f:"",c:"Ops",d:"A test where the tester has no inside knowledge, like an outside attacker."},
{t:"White-box testing",f:"",c:"Ops",d:"A test where the tester has full knowledge of the system."},
{t:"Gray-box testing",f:"",c:"Ops",d:"A test where the tester has partial knowledge of the system."},
{t:"Red team",f:"",c:"Ops",d:"The offensive team that simulates attacks."},
{t:"Blue team",f:"",c:"Ops",d:"The defensive team that detects and responds to attacks."},
{t:"Purple team",f:"",c:"Ops",d:"A collaboration of red and blue teams to improve both attack and defense."},
{t:"Bug bounty",f:"",c:"Ops",d:"A program that pays outside researchers for responsibly reporting vulnerabilities."},
{t:"Baseline",f:"",c:"Ops",d:"A known-good standard configuration used for comparison and hardening."},
{t:"Hardening",f:"",c:"Ops",d:"Reducing a system's attack surface by disabling unneeded features and applying secure settings."},
{t:"Patch management",f:"",c:"Ops",d:"The process of testing and applying software updates to fix vulnerabilities."},
{t:"Change management",f:"",c:"Ops",d:"A formal process for reviewing and approving changes to reduce risk."},
{t:"Sandboxing",f:"",c:"Ops",d:"Running untrusted code in an isolated environment to observe it safely."},
{t:"Allow list",f:"Whitelist",c:"Ops",d:"Permitting only explicitly approved programs or addresses; everything else is blocked."},
{t:"Deny list",f:"Blacklist",c:"Ops",d:"Blocking specific known-bad programs or addresses; everything else is allowed."},
{t:"Threat hunting",f:"",c:"Ops",d:"Proactively searching for hidden threats that evaded automated detection."},

/* ── Incident Response & Forensics ── */
{t:"Incident response",f:"IR",c:"IR",d:"The organized process of preparing for, detecting, and recovering from security incidents."},
{t:"Playbook",f:"",c:"IR",d:"A documented set of steps for responding to a specific type of incident."},
{t:"Runbook",f:"",c:"IR",d:"A detailed operational guide for carrying out a task or response step."},
{t:"Chain of custody",f:"",c:"IR",d:"Documentation tracking who handled evidence and when, to keep it admissible."},
{t:"Order of volatility",f:"",c:"IR",d:"Collecting the most fragile evidence first (like memory) before it disappears."},
{t:"Legal hold",f:"",c:"IR",d:"A duty to preserve data that may be relevant to litigation."},
{t:"E-discovery",f:"Electronic discovery",c:"IR",d:"Finding and producing electronic evidence for legal cases."},
{t:"Digital forensics",f:"",c:"IR",d:"Collecting and analyzing digital evidence after an incident."},
{t:"Root cause analysis",f:"",c:"IR",d:"Determining the underlying reason an incident happened to prevent recurrence."},
{t:"Tabletop exercise",f:"",c:"IR",d:"A discussion-based drill where the team walks through an incident scenario."},

/* ── Governance, Risk & Compliance ── */
{t:"Governance",f:"",c:"GRC",d:"The framework of policies and oversight that directs an organization's security."},
{t:"Policy",f:"",c:"GRC",d:"A high-level rule stating what must be done and why."},
{t:"Standard",f:"",c:"GRC",d:"A mandatory specification of how to meet a policy."},
{t:"Procedure",f:"",c:"GRC",d:"Step-by-step instructions for carrying out a task."},
{t:"AUP",f:"Acceptable Use Policy",c:"GRC",d:"Rules defining how employees may use company systems and data."},
{t:"Risk",f:"",c:"GRC",d:"The chance that a threat exploits a vulnerability, and the resulting impact."},
{t:"Risk assessment",f:"",c:"GRC",d:"The process of identifying, analyzing, and prioritizing risks."},
{t:"Risk register",f:"",c:"GRC",d:"A documented list of identified risks and how they are being handled."},
{t:"Risk appetite",f:"",c:"GRC",d:"The amount of risk an organization is willing to accept."},
{t:"Risk tolerance",f:"",c:"GRC",d:"The acceptable variation around the risk appetite."},
{t:"Risk acceptance",f:"",c:"GRC",d:"Choosing to take no action and live with a risk."},
{t:"Risk avoidance",f:"",c:"GRC",d:"Eliminating a risk by not doing the risky activity."},
{t:"Risk transference",f:"",c:"GRC",d:"Shifting risk to a third party, such as through insurance."},
{t:"Risk mitigation",f:"",c:"GRC",d:"Reducing the likelihood or impact of a risk with controls."},
{t:"Quantitative risk analysis",f:"",c:"GRC",d:"Measuring risk with numbers, like ALE = SLE × ARO."},
{t:"Qualitative risk analysis",f:"",c:"GRC",d:"Rating risk with subjective levels like high, medium, and low."},
{t:"SLE",f:"Single Loss Expectancy",c:"GRC",d:"The expected money lost from a single occurrence of a risk."},
{t:"ALE",f:"Annualized Loss Expectancy",c:"GRC",d:"The expected yearly loss from a risk: SLE multiplied by ARO."},
{t:"ARO",f:"Annualized Rate of Occurrence",c:"GRC",d:"How many times per year a risk is expected to happen."},
{t:"Inherent risk",f:"",c:"GRC",d:"The level of risk before any controls are applied."},
{t:"Residual risk",f:"",c:"GRC",d:"The risk that remains after controls have been applied."},
{t:"RTO",f:"Recovery Time Objective",c:"GRC",d:"The maximum acceptable time to restore a system after an outage."},
{t:"RPO",f:"Recovery Point Objective",c:"GRC",d:"The maximum acceptable amount of data loss measured in time."},
{t:"MTBF",f:"Mean Time Between Failures",c:"GRC",d:"The average time a repairable system runs before it fails."},
{t:"MTTR",f:"Mean Time To Repair",c:"GRC",d:"The average time it takes to fix a failed system."},
{t:"BIA",f:"Business Impact Analysis",c:"GRC",d:"Identifying which functions are critical and the impact if they are disrupted."},
{t:"BCP",f:"Business Continuity Plan",c:"GRC",d:"A plan to keep the business running during and after a disruption."},
{t:"DRP",f:"Disaster Recovery Plan",c:"GRC",d:"A plan for restoring IT systems and data after a disaster."},
{t:"Compliance",f:"",c:"GRC",d:"Meeting required laws, regulations, and standards."},
{t:"Audit",f:"",c:"GRC",d:"A formal review to verify controls are in place and working."},
{t:"Due care",f:"",c:"GRC",d:"Taking reasonable ongoing steps to protect assets."},
{t:"Due diligence",f:"",c:"GRC",d:"Investigating risks before making a decision or agreement."},
{t:"GDPR",f:"General Data Protection Regulation",c:"GRC",d:"The EU law governing the protection and privacy of personal data."},
{t:"HIPAA",f:"Health Insurance Portability and Accountability Act",c:"GRC",d:"US law protecting the privacy and security of health information."},
{t:"PCI DSS",f:"Payment Card Industry Data Security Standard",c:"GRC",d:"Security requirements for organizations that handle credit card data."},
{t:"SLA",f:"Service Level Agreement",c:"GRC",d:"A contract defining the expected level of service, like uptime."},
{t:"MOU",f:"Memorandum of Understanding",c:"GRC",d:"A non-binding agreement outlining intentions between parties."},
{t:"NDA",f:"Non-Disclosure Agreement",c:"GRC",d:"A contract that legally binds parties to keep information confidential."},
{t:"SOW",f:"Statement of Work",c:"GRC",d:"A document detailing the specific work, deliverables, and timeline for a project."},
{t:"MSA",f:"Master Service Agreement",c:"GRC",d:"An overarching contract setting general terms for future work between parties."},
{t:"BPA",f:"Business Partners Agreement",c:"GRC",d:"An agreement defining the terms of a partnership between two businesses."},
{t:"DPO",f:"Data Protection Officer",c:"GRC",d:"The person responsible for an organization's data privacy compliance."},
{t:"Third-party risk",f:"Vendor risk",c:"GRC",d:"The risk introduced by vendors and suppliers with access to your systems or data."},
{t:"Security awareness training",f:"",c:"GRC",d:"Teaching staff to recognize and avoid security threats like phishing."},

/* ── Wireless ── */
{t:"WEP",f:"Wired Equivalent Privacy",c:"Wireless",d:"The original, now-broken Wi-Fi security standard; never use it."},
{t:"WPA",f:"Wi-Fi Protected Access",c:"Wireless",d:"The replacement for WEP; the original WPA is now also outdated."},
{t:"WPA2",f:"Wi-Fi Protected Access 2",c:"Wireless",d:"A widely used Wi-Fi security standard that uses strong AES-CCMP encryption."},
{t:"WPA3",f:"Wi-Fi Protected Access 3",c:"Wireless",d:"The newest Wi-Fi security standard, adding SAE to resist password cracking."},
{t:"PSK",f:"Pre-Shared Key",c:"Wireless",d:"A shared Wi-Fi password used by all users on the network."},
{t:"SAE",f:"Simultaneous Authentication of Equals",c:"Wireless",d:"The WPA3 handshake that protects against offline password guessing."},
{t:"Evil twin",f:"",c:"Wireless",d:"A fake Wi-Fi access point that mimics a real one to steal data."},
{t:"Rogue access point",f:"",c:"Wireless",d:"An unauthorized wireless access point connected to the network."},
{t:"Deauthentication attack",f:"",c:"Wireless",d:"Forcing devices off Wi-Fi, often to capture handshakes or set up an evil twin."},
{t:"Bluejacking",f:"",c:"Wireless",d:"Sending unsolicited messages to a nearby Bluetooth device."},
{t:"Bluesnarfing",f:"",c:"Wireless",d:"Stealing data from a device over a Bluetooth connection."},
{t:"WPS",f:"Wi-Fi Protected Setup",c:"Wireless",d:"An easy Wi-Fi setup feature with a weak PIN that attackers can brute-force; disable it."},
{t:"RFID",f:"Radio Frequency Identification",c:"Wireless",d:"Using radio tags to identify objects or badges; can be cloned if unprotected."},
{t:"NFC",f:"Near Field Communication",c:"Wireless",d:"Very short-range wireless used for contactless payments and pairing."},

/* ── Endpoint & Mobile ── */
{t:"TPM",f:"Trusted Platform Module",c:"Endpoint",d:"A chip on the motherboard that securely stores encryption keys and supports secure boot."},
{t:"Secure boot",f:"",c:"Endpoint",d:"Firmware that checks each boot component's signature so only trusted code loads."},
{t:"Measured boot",f:"",c:"Endpoint",d:"Recording a trusted log of what loaded during boot so changes can be detected."},
{t:"UEFI",f:"Unified Extensible Firmware Interface",c:"Endpoint",d:"Modern firmware that starts a computer and supports security features like secure boot."},
{t:"MDM",f:"Mobile Device Management",c:"Endpoint",d:"Software to centrally configure, secure, and wipe mobile devices."},
{t:"UEM",f:"Unified Endpoint Management",c:"Endpoint",d:"Managing all endpoint types — mobile, laptop, desktop — from one console."},
{t:"BYOD",f:"Bring Your Own Device",c:"Endpoint",d:"Allowing employees to use personal devices for work, which raises security challenges."},
{t:"COPE",f:"Corporate-Owned, Personally Enabled",c:"Endpoint",d:"Company-owned devices that employees may also use for personal tasks."},
{t:"CYOD",f:"Choose Your Own Device",c:"Endpoint",d:"Employees pick from a list of company-approved devices."},
{t:"Geofencing",f:"",c:"Endpoint",d:"Restricting a device's features based on its physical location."},
{t:"Embedded system",f:"",c:"Endpoint",d:"A computer built into a larger device for a specific function, like a router or thermostat."},
{t:"RTOS",f:"Real-Time Operating System",c:"Endpoint",d:"An OS that responds within strict time limits, used in critical and embedded systems."},
{t:"SCADA",f:"Supervisory Control and Data Acquisition",c:"Endpoint",d:"Systems that monitor and control industrial equipment like power and water."},
{t:"ICS",f:"Industrial Control System",c:"Endpoint",d:"Systems that operate industrial processes and machinery."},
{t:"IoT",f:"Internet of Things",c:"Endpoint",d:"Everyday internet-connected devices like cameras and sensors, often weakly secured."},

/* ── Protocols & Ports ── */
{t:"SSH",f:"Secure Shell",c:"Network",d:"An encrypted protocol for secure remote login, file transfer, and tunneling; uses port 22."},
{t:"Telnet",f:"",c:"Network",d:"An old remote-login protocol that sends everything in cleartext on port 23; replaced by SSH."},
{t:"FTP",f:"File Transfer Protocol",c:"Network",d:"Transfers files in cleartext on ports 20 and 21; use SFTP or FTPS instead."},
{t:"SFTP",f:"SSH File Transfer Protocol",c:"Network",d:"Secure file transfer carried over SSH on port 22."},
{t:"FTPS",f:"FTP Secure",c:"Network",d:"FTP secured with TLS, typically on port 990."},
{t:"TFTP",f:"Trivial File Transfer Protocol",c:"Network",d:"A simple, unauthenticated file transfer protocol on UDP port 69; avoid for sensitive data."},
{t:"HTTP",f:"Hypertext Transfer Protocol",c:"Network",d:"Unencrypted web traffic on port 80; use HTTPS instead."},
{t:"HTTPS",f:"HTTP Secure",c:"Network",d:"Web traffic encrypted with TLS on port 443."},
{t:"RDP",f:"Remote Desktop Protocol",c:"Network",d:"Microsoft protocol for remote graphical desktop access on port 3389; keep it off the open internet."},
{t:"SMB",f:"Server Message Block",c:"Network",d:"Windows file and printer sharing protocol on port 445; a common ransomware spread path if exposed."},
{t:"SMTP",f:"Simple Mail Transfer Protocol",c:"Network",d:"Sends email between servers on port 25; secured with TLS on 465 or 587."},
{t:"IMAP",f:"Internet Message Access Protocol",c:"Network",d:"Retrieves email while leaving it on the server (port 143; secure version IMAPS on 993)."},
{t:"POP3",f:"Post Office Protocol 3",c:"Network",d:"Downloads email from a server to one device (port 110; secure version POP3S on 995)."},
{t:"SNMP",f:"Simple Network Management Protocol",c:"Network",d:"Monitors and manages network devices on ports 161 and 162; use SNMPv3 for encryption and authentication."},
{t:"NTP",f:"Network Time Protocol",c:"Network",d:"Synchronizes clocks across devices on UDP port 123; accurate time is vital for logs and certificates."},
{t:"LDAPS",f:"Lightweight Directory Access Protocol Secure",c:"Network",d:"LDAP encrypted with TLS on port 636; the secure replacement for plain LDAP (389)."},
{t:"RDP gateway",f:"",c:"Network",d:"A hardened entry point that brokers Remote Desktop connections so RDP is never exposed directly."},

/* ── Chapter 7: Advanced Attacks, Secure Coding & Automation ── */
{t:"Resource exhaustion",f:"",c:"Threats",d:"Consuming a system's bandwidth, memory, CPU, or connections until it can no longer serve users — the core of a DoS attack."},
{t:"SYN flood",f:"",c:"Threats",d:"A DoS that sends many TCP SYN packets but never completes the handshake, filling the connection table with half-open connections."},
{t:"Reflected DDoS",f:"",c:"Threats",d:"A DDoS where the attacker spoofs the victim's IP so third-party servers send their replies to the victim."},
{t:"Amplified DDoS",f:"",c:"Threats",d:"A reflected DDoS using protocols where a small request triggers a much larger reply (DNS, NTP) to multiply the flood."},
{t:"Indicator",f:"",c:"Threats",d:"An observable sign of an attack, such as a traffic spike, failed logins, or a flood of half-open connections."},
{t:"Spoofing",f:"",c:"Threats",d:"Falsifying an identifier such as a source IP, MAC, email address, or caller ID to impersonate a trusted source."},
{t:"Forgery",f:"",c:"Threats",d:"Creating fraudulent data, such as a forged request, token, or certificate, so a system treats it as genuine."},
{t:"Attacker-in-the-browser",f:"Man-in-the-Browser",c:"Threats",d:"Malware inside the browser that alters pages and transactions after TLS has decrypted them, so encryption cannot stop it."},
{t:"SSL stripping",f:"",c:"Threats",d:"An on-path attack that downgrades a victim's HTTPS connection to plain HTTP so traffic can be read in cleartext; HSTS prevents it."},
{t:"Credential replay",f:"",c:"Threats",d:"A replay attack that reuses captured authentication data such as a hash, ticket, or token to log in without the password."},
{t:"URL",f:"Uniform Resource Locator",c:"Network",d:"The full web address used to locate a resource on the internet."},
{t:"URL redirection",f:"",c:"Threats",d:"Sending a user to a different destination than expected, often via a malicious link or an open redirect on a trusted site."},
{t:"Domain hijacking",f:"",c:"Threats",d:"Taking control of a domain's registration to reroute all of its traffic, often via stolen registrar credentials."},
{t:"DNS filtering",f:"",c:"Network",d:"Blocking resolution of known-malicious or policy-violating domains so users cannot reach them."},
{t:"DNS log files",f:"",c:"Ops",d:"Records of the DNS queries a network makes, used to detect beaconing, data exfiltration, and infected hosts."},
{t:"Input validation",f:"",c:"Ops",d:"Checking that input matches the expected type, length, format, and range before use; the top defense against injection."},
{t:"Client-side validation",f:"",c:"Ops",d:"Input checking done in the browser for fast feedback; easily bypassed, so never relied on for security."},
{t:"Server-side validation",f:"",c:"Ops",d:"Input checking done on the server where an attacker cannot tamper with it; the authoritative check."},
{t:"HTML escaping",f:"Output encoding",c:"Ops",d:"Converting special characters into safe entities so user input renders as text, not code; prevents XSS."},
{t:"Error handling",f:"",c:"Ops",d:"Catching errors and returning generic messages so attackers don't see stack traces, paths, or database details."},
{t:"Code obfuscation",f:"",c:"Ops",d:"Deliberately making code hard to read or reverse-engineer; raises the bar for attackers but is not a real control."},
{t:"Compiler",f:"",c:"Ops",d:"A tool that translates human-written source code into executable machine code."},
{t:"Outsourced code",f:"",c:"Ops",d:"Third-party, contracted, or library code you didn't write, which can introduce flaws or backdoors if not reviewed."},
{t:"HTTP headers",f:"",c:"Ops",d:"Metadata sent with web requests and responses — general, request, and entity headers, plus security headers like HSTS and CSP."},
{t:"Cookie",f:"",c:"Network",d:"A small piece of data stored in the browser to maintain session state between requests."},
{t:"Secure cookie",f:"",c:"Ops",d:"A cookie marked Secure (sent only over HTTPS) and usually HttpOnly (hidden from JavaScript) to resist theft."},
{t:"Code signing",f:"",c:"Crypto",d:"Digitally signing software with the publisher's key so users can verify its authenticity and integrity."},
{t:"OWASP",f:"Open Worldwide Application Security Project",c:"Ops",d:"A nonprofit known for the OWASP Top 10 list of the most critical web application security risks."},
{t:"Static code analysis",f:"SAST",c:"Ops",d:"Inspecting source code without running it to find flaws early in development."},
{t:"Dynamic code analysis",f:"DAST",c:"Ops",d:"Testing an application while it runs to find flaws that appear only at runtime."},
{t:"Manual code review",f:"",c:"Ops",d:"Humans reading code line by line to catch logic and design flaws that automated tools miss."},
{t:"Fuzzing",f:"",c:"Ops",d:"Feeding large amounts of random or malformed input to an application to find crashes and unhandled cases."},
{t:"Package monitoring",f:"",c:"Ops",d:"Watching third-party dependencies for known vulnerabilities and tampering to protect the software supply chain."},
{t:"Stored procedure",f:"",c:"Ops",d:"Reusable SQL stored in the database; when parameterized it binds input as data and helps prevent SQL injection."},
{t:"Parameterized query",f:"",c:"Ops",d:"A query that binds user input as data rather than executable SQL — the definitive fix for SQL injection."},
{t:"Integer overflow",f:"",c:"Threats",d:"When a value exceeds its data type's maximum and wraps around, which can cause memory-corruption bugs."},
{t:"Memory leak",f:"",c:"Threats",d:"Failing to free memory no longer needed until an application gradually exhausts available memory."},
{t:"DLL",f:"Dynamic Link Library",c:"Endpoint",d:"A shared library of code that Windows programs load at runtime."},
{t:"DLL injection",f:"",c:"Threats",d:"Forcing a process to load a malicious Dynamic Link Library so the attacker's code runs in its context."},
{t:"LDAP injection",f:"",c:"Threats",d:"Injecting crafted input into LDAP directory queries to bypass authentication or read the directory."},
{t:"XML injection",f:"",c:"Threats",d:"Injecting malicious content into XML input or documents, including XML External Entity (XXE) attacks."},
{t:"Reflected XSS",f:"",c:"Threats",d:"Cross-site scripting where a script in a request is reflected back and runs in the victim's browser via a crafted link."},
{t:"Stored XSS",f:"",c:"Threats",d:"Cross-site scripting where a script saved on the server runs for every visitor who views the page."},
{t:"Web server logs",f:"",c:"Ops",d:"Records of every request to a web server; key evidence for spotting injection and directory-traversal attempts."},
{t:"Guardrails",f:"",c:"Ops",d:"Automated policy limits that prevent unsafe actions, such as blocking creation of a public storage bucket."},
{t:"Security groups",f:"",c:"Cloud",d:"Programmatically managed firewall/access rules that control traffic to cloud resources."},
{t:"CI/CD",f:"Continuous Integration / Continuous Deployment",c:"Ops",d:"Automatically building, testing, and deploying code on every change to catch defects early and ship consistently."},
{t:"User provisioning",f:"",c:"Ops",d:"Automatically creating, modifying, and disabling user accounts as people join, move, or leave the organization."},

/* ── Chapter 9: Controls, Resilience & Physical Security ── */
/* Physical Security — Ops */
{t:"Access badge",f:"",c:"Ops",d:"An RFID or smart-card credential worn or carried by personnel that grants access to secured areas when presented to a reader."},
{t:"Security guards",f:"",c:"Ops",d:"Human security personnel who deter, detect, and respond to physical threats — the most flexible physical security control because they can use judgment."},
{t:"Video surveillance",f:"CCTV",c:"Ops",d:"Closed-circuit cameras that record and monitor physical areas. Serves as both a deterrent and a detective control; footage provides forensic evidence after an incident."},
{t:"Motion detection",f:"",c:"Ops",d:"A sensor that triggers an alert when it detects movement in a monitored area, typically using passive infrared, microwave, or ultrasonic technology."},
{t:"Noise detection",f:"",c:"Ops",d:"A sensor that triggers when ambient sound exceeds a set threshold — used to detect glass breaking, gunshots, or forced entry."},
{t:"Infrared detection",f:"",c:"Ops",d:"A sensor that detects heat signatures (thermal radiation) emitted by people or objects, used for perimeter security and after-hours monitoring."},
{t:"Pressure detection",f:"",c:"Ops",d:"A sensor embedded in floors or surfaces that triggers when weight is applied — used to detect unauthorized movement through a secured area."},
{t:"Microwave detection",f:"",c:"Ops",d:"A sensor that emits microwave pulses and measures reflections to detect movement; can cover large open areas and works in darkness."},
{t:"Ultrasonic detection",f:"",c:"Ops",d:"A sensor that emits ultrasonic sound waves and detects Doppler shifts caused by movement in the monitored space."},
{t:"Dual gate",f:"",c:"Ops",d:"A two-gate vehicle entry system where the second gate cannot open until the first is fully closed and the vehicle is verified — prevents tailgating at vehicle checkpoints."},
{t:"Lighting",f:"",c:"Ops",d:"Security lighting that eliminates dark areas around a facility, deterring unauthorized access and supporting CCTV effectiveness at night."},
{t:"Alarms",f:"",c:"Ops",d:"Detection systems that alert security personnel when a sensor is triggered — can be silent (notify guards remotely) or audible (deter intruders directly)."},
{t:"Access control vestibule",f:"Mantrap",c:"Ops",d:"A two-door entry system where the first door must close and lock before the second door can open, preventing tailgating into secured facilities."},
/* Physical Attacks — Threats */
{t:"Credit card skimming",f:"",c:"Threats",d:"Attaching a hidden device to a legitimate payment terminal to capture magnetic stripe data from victims' cards without their knowledge."},
{t:"Card cloning",f:"",c:"Threats",d:"Creating a duplicate payment card using data captured by a skimmer — the physical card produced from stolen skimming data."},
{t:"Physical brute force",f:"",c:"Threats",d:"Using physical force to bypass access controls — breaking locks, ramming doors, or destroying barriers to gain unauthorized entry."},
{t:"Environmental attack",f:"",c:"Threats",d:"Targeting the physical environment that supports IT systems — disrupting power, cooling, fire suppression, or flooding to take down systems without touching them directly."},
/* Asset Management — GRC */
{t:"Asset management",f:"",c:"GRC",d:"The systematic process of tracking, maintaining, and protecting all organizational assets through their entire lifecycle from acquisition to disposal."},
{t:"Hardware asset management",f:"",c:"GRC",d:"Tracking physical devices (servers, laptops, switches) by serial number, location, owner, and status throughout their lifecycle."},
{t:"Software asset management",f:"",c:"GRC",d:"Tracking software licenses, versions, and installation counts to ensure compliance and identify unauthorized or outdated software."},
{t:"Data asset management",f:"",c:"GRC",d:"Managing data through classification, ownership assignment, retention policies, and secure disposal to protect sensitive information."},
/* Asset Vulnerabilities — Threats */
{t:"Architecture and design weaknesses",f:"",c:"Threats",d:"Security flaws baked into a system's fundamental design rather than introduced later — these are harder to fix because remediation often requires redesigning the system."},
{t:"System sprawl",f:"",c:"Threats",d:"Uncontrolled growth of systems, servers, and VMs without adequate tracking or governance, expanding the attack surface and creating unmanaged risk."},
/* Defense in Depth — Core */
{t:"Vendor diversity",f:"",c:"Core",d:"Using products from multiple vendors across security layers so a zero-day or breach in one vendor's product does not compromise all defenses simultaneously."},
{t:"Technology diversity",f:"",c:"Core",d:"Deploying different technologies at different layers of the security stack so attackers cannot exploit a single technique across all layers."},
{t:"Control diversity",f:"",c:"Core",d:"Applying a mix of preventive, detective, corrective, and deterrent controls so that if one type of control fails, others still provide protection."},
{t:"Mission essential functions",f:"",c:"Core",d:"The critical business processes that must continue operating during a disruption — identified during the BIA and prioritized in the BCP."},
/* RAID Levels — Ops */
{t:"RAID-0",f:"",c:"Ops",d:"Disk striping across 2+ drives with no redundancy — highest performance and full capacity utilization, but any single drive failure causes total data loss."},
{t:"RAID-1",f:"",c:"Ops",d:"Disk mirroring across exactly 2 drives — identical data on both, so if one fails the other has a complete copy. Uses 50% of total capacity."},
{t:"RAID-5",f:"",c:"Ops",d:"Striping with distributed parity across 3+ drives — can survive the loss of any one drive. A good balance of performance, capacity, and redundancy."},
{t:"RAID-6",f:"",c:"Ops",d:"Striping with double distributed parity across 4+ drives — can survive the simultaneous loss of any two drives. More resilient than RAID-5 at the cost of write performance."},
{t:"RAID-10",f:"RAID 1+0",c:"Ops",d:"A combination of mirroring and striping across 4+ drives — provides high performance from striping and fault tolerance from mirroring. Can lose one drive per mirror pair."},
/* HA & Load Balancing — Ops */
{t:"Active/active load balancing",f:"",c:"Ops",d:"A load balancing configuration where all nodes handle live traffic simultaneously, maximizing throughput and resource utilization."},
{t:"Active/passive load balancing",f:"",c:"Ops",d:"A load balancing configuration where one or more standby nodes sit idle and only take over traffic if an active node fails."},
{t:"Software load balancer",f:"",c:"Ops",d:"A load balancing solution that runs as software or a virtual machine rather than dedicated hardware, offering flexibility and lower cost."},
{t:"Clustering",f:"",c:"Ops",d:"Grouping multiple servers into a single logical unit that appears as one system to users — provides high availability and scalability."},
{t:"NIC teaming",f:"Link aggregation",c:"Ops",d:"Bonding two or more physical network interface cards into one logical interface for redundancy (failover if one NIC fails) and/or increased bandwidth."},
/* Power — Ops */
{t:"UPS",f:"Uninterruptible Power Supply",c:"Ops",d:"A battery-backed device that provides immediate power during a brief outage or fluctuation, giving servers time to stay online or shut down gracefully."},
{t:"Dual power supply",f:"",c:"Ops",d:"Two separate power supply units inside a single server, each connected to an independent power source — if one fails, the other keeps the server running."},
{t:"Generator",f:"",c:"Ops",d:"A fuel-powered device that produces electricity to sustain a facility during extended power outages after the UPS battery is depleted."},
{t:"Managed PDU",f:"Managed Power Distribution Unit",c:"Ops",d:"A smart power strip that distributes electricity to rack equipment with remote monitoring and per-outlet control, enabling administrators to cycle power or track consumption remotely."},
/* Backup Media — Data */
{t:"NAS",f:"Network Attached Storage",c:"Data",d:"A file-level storage device connected to a network so multiple clients can read and write files — commonly used as a backup destination."},
{t:"SAN",f:"Storage Area Network",c:"Data",d:"A dedicated high-speed network providing block-level storage to servers — appears to the OS as a locally attached drive; used in enterprise backup and DR."},
{t:"Cloud storage",f:"",c:"Data",d:"Storing data on remote servers managed by a cloud provider, offering geographically distributed, scalable backup without on-premises hardware."},
{t:"Online backup",f:"",c:"Data",d:"Backup data that is immediately accessible for restore — typically on disk, NAS, or cloud storage. Fast restore but potentially vulnerable to ransomware if connected."},
{t:"Offline backup",f:"",c:"Data",d:"Backup data on disconnected media (tape, removable disk) that is physically isolated from the network — immune to ransomware but slower to restore."},
{t:"Offsite backup",f:"",c:"Data",d:"Backup copies stored at a geographically separate location to ensure data survives a site-wide disaster like a fire, flood, or power failure."},
{t:"3-2-1 rule",f:"",c:"Data",d:"The backup best practice: keep 3 copies of data, on 2 different media types, with 1 copy stored offsite — protects against media failure, local disaster, and single points of failure simultaneously."},
/* Backup Types — Ops */
{t:"Full backup",f:"",c:"Ops",d:"A complete copy of all selected data. Slowest to create and uses the most storage, but the fastest to restore because only one backup set is needed."},
{t:"Differential backup",f:"",c:"Ops",d:"Backs up all data changed since the last full backup. Faster to create than a full; restore requires the last full backup plus the most recent differential only."},
{t:"Incremental backup",f:"",c:"Ops",d:"Backs up only data changed since the last backup of any type. Fastest to create and uses least storage, but restore is slowest — requires the full backup plus every incremental in sequence."},
{t:"Snapshot backup",f:"",c:"Ops",d:"A point-in-time copy of a system's state, often at the storage or hypervisor layer — very fast to create and can restore nearly instantly, but typically kept short-term."},
{t:"Replication",f:"",c:"Ops",d:"Continuously or near-continuously copying data to a secondary location so the replica stays in sync — provides near-zero RPO when done synchronously."},
{t:"Journaling",f:"",c:"Ops",d:"Recording every change made to a database or file system as a sequential log — the journal can be replayed to recover data or verify consistency after a crash."},
/* Database Backup Context — Ops */
{t:"Hot backup (database)",f:"",c:"Ops",d:"A backup taken while the database is fully online and serving transactions — users are unaffected. Requires special tooling to ensure consistency. Not the same as a hot DR site."},
{t:"Warm backup (database)",f:"",c:"Ops",d:"A backup taken while the database is partially offline — some services are paused to ensure consistency, but a full shutdown is not required. Not the same as a warm DR site."},
{t:"Cold backup (database)",f:"",c:"Ops",d:"A backup taken while the database is completely shut down — the most consistent backup type, but requires downtime. Not the same as a cold DR site."},
/* Recovery Sites — Ops */
{t:"Hot site",f:"",c:"Ops",d:"A fully operational DR facility with live, up-to-date data and hardware that can assume production operations within minutes to hours. The most expensive DR option."},
{t:"Warm site",f:"",c:"Ops",d:"A DR facility with hardware in place but requiring data restoration before going live — recovery takes hours to days. A cost-effective middle ground."},
{t:"Cold site",f:"",c:"Ops",d:"A DR facility with only basic utilities (power, network) and no equipment or data — the cheapest option but slowest to activate, taking days to weeks."},
{t:"Mobile site",f:"",c:"Ops",d:"A portable DR facility (trailer, container) that can be deployed to any location — flexible and useful when fixed sites are unavailable or impractical."},
{t:"Site resiliency",f:"",c:"Ops",d:"The overall capability of an organization's DR sites to sustain operations and recover quickly when the primary site fails."},
{t:"COOP",f:"Continuity of Operations Planning",c:"Ops",d:"A plan that ensures mission-essential functions continue from an alternate location or with alternate staff during a disruption to the primary facility."},
/* DR Testing — Ops */
{t:"Simulations",f:"",c:"Ops",d:"A DR test where the team actively responds to a realistic mock disaster scenario — more hands-on than a tabletop but without cutting over to the actual recovery system."},
{t:"Parallel processing",f:"",c:"Ops",d:"A DR test where the recovery system runs alongside production simultaneously; outputs are compared to verify the recovery system can handle production load before committing to cutover."},
{t:"Failover test",f:"",c:"Ops",d:"A DR test where production traffic actually switches to the recovery system — the most realistic and highest-risk test type."},
{t:"Restoration",f:"",c:"Ops",d:"The process of returning systems and data to normal operation at the primary site after a disruption, following a disaster recovery or backup event."},
/* Capacity Planning — Ops */
{t:"Capacity planning",f:"",c:"Ops",d:"Proactively determining whether an organization will have sufficient people, technology, and infrastructure to handle current and future workload demands."}
];

