const NODE_DATA = {
'hids':{title:'HIDS — Host-Based IDS',cat:'IDS / IPS',html:`<p>An IDS installed <strong>directly on a host</strong> that monitors that system's activity — logs, file changes, processes.</p><h4>What It Monitors</h4><ul><li>System calls and process activity</li><li>File integrity changes</li><li>Login attempts and privilege escalation</li><li>Registry changes (Windows)</li></ul><div class="exam-tip">HIDS can detect attacks that bypass network sensors (encrypted traffic, insider threats). Cannot see other hosts' traffic.</div>`},
'nids':{title:'NIDS — Network-Based IDS',cat:'IDS / IPS',html:`<p>A sensor placed on the <strong>network</strong> that monitors traffic flowing through a segment.</p><h4>Placement</h4><ul><li>Connected to SPAN port or network tap</li><li>Sees all traffic on that segment</li><li>Cannot see encrypted payload without decryption</li></ul><div class="exam-tip">NIDS is passive — it monitors, alerts, but does not block. Add IPS for blocking capability.</div>`},
'sig-ids':{title:'Signature-Based IDS',cat:'IDS / IPS',html:`<p>Detects attacks by matching traffic against a <strong>database of known attack patterns</strong>.</p><h4>Pros / Cons</h4><ul><li>Low false positives — known patterns only</li><li>Fast detection for known threats</li><li>Cannot detect zero-day or novel attacks</li><li>Requires constant signature updates</li></ul><div class="exam-tip">Signature-based = known threats only. Anomaly/trend-based = catches zero-days but more false positives.</div>`},
'trend-ids':{title:'Trend-Based / Anomaly IDS',cat:'IDS / IPS',html:`<p>Establishes a <strong>baseline of normal behavior</strong>, then alerts on deviations from that baseline.</p><h4>Pros / Cons</h4><ul><li>Can detect zero-day and unknown attacks</li><li>Higher false positive rate</li><li>Requires a learning/baselining period</li></ul><div class="exam-tip">Also called anomaly-based or behavior-based IDS. Best used alongside signature-based for layered detection.</div>`},
'zero-day':{title:'Zero-Day Vulnerability',cat:'Advanced Threats',html:`<p>A vulnerability that is <strong>unknown to the vendor</strong> — no patch exists at time of exploitation.</p><h4>Timeline</h4><ul><li>Attacker discovers vulnerability</li><li>Exploit developed and used ("zero days" of protection)</li><li>Vendor eventually discovers and patches</li></ul><div class="exam-tip">Zero-days defeat signature-based IDS. Trend-based / anomaly IDS is the best technical defense since it detects unusual behavior rather than known signatures.</div>`},
'aggregator':{title:'Aggregator',cat:'IDS / IPS',html:`<p>A device or system that <strong>collects and consolidates data from multiple IDS/IPS sensors</strong> for centralized analysis.</p><h4>Function</h4><ul><li>Receives alerts from distributed sensors</li><li>Normalizes and correlates events</li><li>Forwards to SIEM for deeper analysis</li></ul><div class="exam-tip">Aggregators reduce noise and combine distributed sensor data. They sit between sensors and the SIEM in many architectures.</div>`},
'ids-ref':{title:'IDS / IPS',cat:'Reference',html:`<div class="ref-note">Base concept covered in Chapter 1 (SIEM & Detection). This chapter expands with HIDS, NIDS, sensor types, and detection methods.</div>`},
'port-mirror':{title:'Port Mirroring (SPAN)',cat:'NIDS Sensors',html:`<p>A switch feature that <strong>copies traffic from one or more ports to a monitoring port</strong> — SPAN (Switched Port Analyzer).</p><h4>Details</h4><ul><li>Software-configured on managed switches</li><li>Copies frames to NIDS sensor port</li><li>May drop frames under heavy load</li><li>Does not add latency to production traffic</li></ul><div class="exam-tip">Port mirroring is passive and out-of-band — it can miss traffic under load. Port tap is more reliable for forensics.</div>`},
'port-tap':{title:'Port Tap',cat:'NIDS Sensors',html:`<p>A <strong>physical hardware device</strong> inserted inline on a network cable that passively copies all traffic to a monitoring port.</p><h4>Advantages over SPAN</h4><ul><li>Captures 100% of traffic — never drops frames</li><li>Completely passive — undetectable</li><li>Captures errors and malformed frames</li><li>No switch configuration needed</li></ul><div class="exam-tip">Taps are preferred for forensic captures. SPAN ports are easier to set up. Taps require physical access to the cable.</div>`},
'apt':{title:'APT — Advanced Persistent Threat',cat:'Advanced Threats',html:`<p>A sophisticated, long-term attack campaign by a skilled adversary — often nation-state or criminal organization — that <strong>maintains persistent access</strong> to a target.</p><h4>Characteristics</h4><ul><li>Advanced: custom tools, zero-days</li><li>Persistent: months or years of access</li><li>Targeted: specific organization or sector</li><li>Stealthy: evades detection</li></ul><h4>Examples</h4><ul><li>APT29 (Cozy Bear), APT41 (China), Lazarus Group (DPRK)</li></ul><div class="exam-tip">APTs use multiple phases: reconnaissance, initial access, lateral movement, data exfiltration. Honeypots can detect them early.</div>`},
'honeypot':{title:'Honeypot',cat:'Deception Technologies',html:`<p>A <strong>fake system designed to attract attackers</strong> — looks like a real target but is isolated and monitored.</p><h4>Types</h4><ul><li><strong>Low-interaction</strong>: simulated services, low risk</li><li><strong>High-interaction</strong>: real OS, captures full attack behavior</li></ul><h4>Value</h4><ul><li>Early warning of attacks</li><li>Intelligence gathering on attacker TTPs</li><li>Wastes attacker time and resources</li></ul><div class="exam-tip">Honeypots are detective controls. Any connection to a honeypot is suspicious by definition — no legitimate user should access it.</div>`},
'honeynet':{title:'Honeynet',cat:'Deception Technologies',html:`<p>A <strong>network of multiple honeypots</strong> that simulates an entire environment — servers, workstations, routers.</p><div class="exam-tip">Honeynets provide richer intelligence than single honeypots. Attackers can move laterally, revealing their full TTPs and tooling.</div>`},
'honeyfile':{title:'Honey File',cat:'Deception Technologies',html:`<p>A <strong>fake document placed on systems</strong> to detect unauthorized access. If the file is opened, an alert fires.</p><h4>Examples</h4><ul><li>Fake "passwords.xlsx" on a file share</li><li>Document with an embedded tracking pixel or URL</li></ul><div class="exam-tip">Honey files detect insider threats and ransomware (ransomware encrypts them first). Also called canary files.</div>`},
'honeytoken':{title:'Honey Token',cat:'Deception Technologies',html:`<p>A <strong>fake digital credential, API key, or data record</strong> that alerts when used.</p><h4>Examples</h4><ul><li>Fake AWS keys in a code repo</li><li>Fake user account in Active Directory</li><li>Fake credit card number in a database</li></ul><div class="exam-tip">Honey tokens are excellent for detecting credential theft and database breaches. No legitimate process should ever use them.</div>`},
'wlan':{title:'WLAN — Wireless LAN',cat:'Wireless Fundamentals',html:`<p>A <strong>local area network using wireless (radio) transmission</strong> instead of physical cables.</p><h4>Components</h4><ul><li>Access Points (APs) — transmit/receive</li><li>Wireless NICs on client devices</li><li>Controller (enterprise) or standalone AP (home)</li></ul><div class="exam-tip">WLANs are inherently broadcast — any device in range can receive frames. This is why encryption (WPA2/3) is essential.</div>`},
'ap':{title:'Access Point (AP)',cat:'Wireless Fundamentals',html:`<p>A device that creates a <strong>wireless network and bridges wireless clients to the wired network</strong>.</p><h4>Modes</h4><ul><li><strong>Standalone/Fat AP</strong> — self-configured</li><li><strong>Thin AP</strong> — managed by wireless controller</li><li><strong>Mesh AP</strong> — backhaul via wireless</li></ul><div class="exam-tip">Rogue APs are unauthorized access points attached to the network. Wireless IDS and 802.1X port authentication detect and prevent them.</div>`},
'ssid':{title:'SSID — Service Set Identifier',cat:'Wireless Fundamentals',html:`<p>The <strong>name of a wireless network</strong> broadcast in beacon frames by an AP.</p><h4>Security Notes</h4><ul><li>Hiding SSID (disabling broadcast) provides no real security</li><li>Tools like Kismet easily detect hidden SSIDs from probe requests</li><li>SSID is not authentication</li></ul><div class="exam-tip">SSID hiding is security through obscurity — not a real control. Use WPA2/3 for actual security.</div>`},
'mac-addr':{title:'MAC Address',cat:'Wireless Fundamentals',html:`<p>A <strong>48-bit hardware address</strong> burned into every NIC — used for L2 identification on the wireless network.</p><h4>Format</h4><p><code>AA:BB:CC:DD:EE:FF</code> — first 3 bytes = OUI (manufacturer)</p><div class="exam-tip">MAC addresses can be spoofed with software tools. MAC filtering is a deterrent, not a strong security control.</div>`},
'mac-filter':{title:'MAC Filtering',cat:'Wireless Fundamentals',html:`<p>AP configuration that <strong>only allows connections from pre-approved MAC addresses</strong>.</p><h4>Weakness</h4><ul><li>MACs broadcast in cleartext — easily sniffed</li><li>Attacker sniffs an approved MAC, spoofs it</li><li>Adds management overhead for no real security</li></ul><div class="exam-tip">MAC filtering is a deterrent-level control only. It slows down script kiddies but not skilled attackers. Not a substitute for WPA2/3.</div>`},
'net-bands':{title:'Network Bands',cat:'Wireless Fundamentals',html:`<p>Wireless operates on different <strong>radio frequency bands</strong>, each with different range/speed tradeoffs.</p><h4>Bands</h4><ul><li><strong>2.4 GHz</strong> — longer range, more interference, slower (b/g/n)</li><li><strong>5 GHz</strong> — shorter range, less interference, faster (a/n/ac)</li><li><strong>6 GHz</strong> — WiFi 6E only, fastest, least interference</li></ul><div class="exam-tip">2.4 GHz has only 3 non-overlapping channels (1, 6, 11). 5 GHz has many more non-overlapping channels.</div>`},
'wifi-std':{title:'Wireless Standards (802.11)',cat:'Wireless Fundamentals',html:`<p>IEEE 802.11 family defines wireless networking standards.</p><h4>Key Standards</h4><ul><li><strong>802.11a</strong> — 5 GHz, 54 Mbps</li><li><strong>802.11b</strong> — 2.4 GHz, 11 Mbps</li><li><strong>802.11g</strong> — 2.4 GHz, 54 Mbps</li><li><strong>802.11n (WiFi 4)</strong> — 2.4/5 GHz, 600 Mbps, MIMO</li><li><strong>802.11ac (WiFi 5)</strong> — 5 GHz, multi-Gbps</li><li><strong>802.11ax (WiFi 6/6E)</strong> — 2.4/5/6 GHz, OFDMA</li></ul><div class="exam-tip">802.11i is the security amendment (WPA2). 802.11w protects management frames (prevents disassociation attacks).</div>`},
'site-survey':{title:'Site Survey',cat:'Site Survey Tools',html:`<p>A systematic process to <strong>assess the wireless environment</strong> before deploying or auditing a WLAN.</p><h4>Steps</h4><ul><li>Walk the facility measuring signal strength</li><li>Identify dead zones and interference sources</li><li>Determine optimal AP placement</li><li>Document findings in a heat map</li></ul><div class="exam-tip">Site surveys are performed before and after wireless deployments. They identify coverage gaps, interference, and rogue APs.</div>`},
'wifi-analyzer':{title:'WiFi Analyzer',cat:'Site Survey Tools',html:`<p>Software/hardware tool that <strong>scans and displays nearby wireless networks</strong> and their properties.</p><h4>Shows</h4><ul><li>All visible SSIDs (including hidden)</li><li>Signal strength (dBm), channel, band</li><li>Security type (Open, WPA2, WPA3)</li><li>Channel congestion and overlap</li></ul><div class="exam-tip">WiFi analyzers detect rogue APs, evil twins, and channel interference. Tools: Kismet, inSSIDer, NetSpot.</div>`},
'heat-map':{title:'Heat Map',cat:'Site Survey Tools',html:`<p>A <strong>visual overlay on a floor plan</strong> showing wireless signal strength across a physical space.</p><h4>Colors</h4><ul><li>Red/orange = strong signal</li><li>Yellow = moderate signal</li><li>Blue/purple = weak signal</li></ul><div class="exam-tip">Heat maps guide AP placement and identify coverage gaps. Required documentation for enterprise wireless deployments.</div>`},
'wireless-footprint':{title:'Wireless Footprinting',cat:'Site Survey Tools',html:`<p>Documenting the <strong>extent and characteristics of a wireless network's RF coverage</strong>.</p><h4>Includes</h4><ul><li>Signal coverage boundaries (where it leaks outside)</li><li>All APs, SSIDs, and channels in use</li><li>Interference sources identified</li></ul><div class="exam-tip">Wireless footprinting identifies signal leakage outside the building — attackers can connect from parking lots if signals extend too far.</div>`},
'omni-antenna':{title:'Omnidirectional Antenna',cat:'Site Survey Tools',html:`<p>An antenna that <strong>radiates signal equally in all horizontal directions</strong> — 360° coverage pattern.</p><h4>Use Cases</h4><ul><li>General office / floor coverage</li><li>Default antenna on most APs</li></ul><div class="exam-tip">Omnidirectional = 360° spread. Directional = focused beam. Omnidirectional leaks signal in all directions — consider signal containment for secure areas.</div>`},
'dir-antenna':{title:'Directional Antenna',cat:'Site Survey Tools',html:`<p>An antenna that <strong>focuses RF energy in a specific direction</strong> for longer range point-to-point links.</p><h4>Types</h4><ul><li><strong>Yagi</strong> — narrow beam, long range</li><li><strong>Parabolic</strong> — very long range, building-to-building</li><li><strong>Patch</strong> — moderate beam width</li></ul><div class="exam-tip">Directional antennas are used for building-to-building wireless links and war driving (extend capture range).</div>`},
'wep':{title:'WEP — Wired Equivalent Privacy',cat:'Deprecated Wireless',html:`<p>The <strong>original 802.11 security protocol</strong> — completely broken and must not be used.</p><h4>Why It Fails</h4><ul><li>Uses RC4 stream cipher with weak 24-bit IV</li><li>IVs repeat after ~16 million packets</li><li>Repeated IVs allow key recovery (IV attack)</li><li>Crackable in minutes with tools like aircrack-ng</li></ul><div class="exam-tip">WEP is broken by the IV (Initialization Vector) attack. If you see WEP on the exam, it is always the wrong choice for security.</div>`},
'wpa':{title:'WPA — WiFi Protected Access',cat:'Deprecated Wireless',html:`<p>The <strong>interim replacement for WEP</strong> using TKIP encryption — now deprecated.</p><h4>Why Deprecated</h4><ul><li>TKIP still based on RC4</li><li>Vulnerable to TKIP MIC attack</li><li>Replaced by WPA2 (AES/CCMP)</li></ul><div class="exam-tip">WPA/TKIP is deprecated. Always choose WPA2 (AES/CCMP) or WPA3. TKIP was a temporary fix while 802.11i was finalized.</div>`},
'wpa2':{title:'WPA2 — IEEE 802.11i',cat:'WPA2',html:`<p>The <strong>current wireless security standard</strong> using AES encryption with CCMP.</p><h4>Key Features</h4><ul><li>AES-CCMP encryption (128-bit)</li><li>Two modes: Personal (PSK) and Enterprise (RADIUS)</li><li>Defined in IEEE 802.11i amendment</li></ul><h4>Weakness</h4><ul><li>PMKID attack on PSK mode allows offline cracking</li><li>KRACK attack (patched) on 4-way handshake</li></ul><div class="exam-tip">WPA2-Enterprise (802.1X + RADIUS) is more secure than WPA2-Personal (PSK). PSK can be offline-cracked if captured handshake + weak password.</div>`},
'psk':{title:'Pre-Shared Key (PSK)',cat:'WPA2',html:`<p>A <strong>shared passphrase</strong> configured on both the AP and client — used in WPA2/3 Personal mode.</p><h4>How It Works</h4><ul><li>Passphrase converted to 256-bit PMK via PBKDF2</li><li>PMK used in 4-way handshake to derive PTK</li><li>Handshake can be captured and cracked offline</li></ul><div class="exam-tip">PSK is only as strong as the passphrase. Use 20+ character random passphrases. WPA3-SAE eliminates offline dictionary attacks against PSK.</div>`},
'open-mode':{title:'Open Mode (Wireless)',cat:'WPA2',html:`<p>AP configuration that <strong>requires no authentication</strong> — any device can connect.</p><ul><li>Public hotspots, guest WiFi</li><li>No encryption (WPA2 open) or OWE encryption (WPA3 Enhanced Open)</li></ul><div class="exam-tip">Open mode with WPA2 = no encryption. Open mode with WPA3 Enhanced Open = OWE encryption (opportunistic). Never use WPA2 open mode for sensitive networks.</div>`},
'enterprise-mode':{title:'Enterprise Mode (Wireless)',cat:'WPA2',html:`<p>Uses <strong>IEEE 802.1X + RADIUS</strong> for per-user authentication instead of a shared passphrase.</p><h4>Advantages</h4><ul><li>Individual credentials per user</li><li>Certificates or MFA possible</li><li>Revoke one user without changing network password</li><li>Per-user encryption keys</li></ul><div class="exam-tip">Enterprise mode is always preferred in corporate environments. Each user has unique credentials — compromise of one doesn't affect others.</div>`},
'shared-secret':{title:'Shared Secret (RADIUS)',cat:'WPA2',html:`<p>A <strong>password shared between the AP (RADIUS client) and the RADIUS server</strong> to authenticate the AP itself.</p><div class="exam-tip">The shared secret authenticates the AP to RADIUS — separate from user credentials. A weak shared secret allows rogue APs to impersonate legitimate ones.</div>`},
'radius-ref':{title:'RADIUS Server',cat:'Reference',html:`<div class="ref-note">Covered in Chapter 2 (SSO & Federation) and Chapter 3 (Firewall & Perimeter). In Chapter 4, RADIUS authenticates wireless users in Enterprise mode via 802.1X.</div>`},
'wpa3':{title:'WPA3',cat:'WPA3',html:`<p>The <strong>latest WiFi security standard</strong> — replaces WPA2 with stronger handshake and encryption.</p><h4>Improvements over WPA2</h4><ul><li>SAE replaces PSK 4-way handshake — resistant to offline attacks</li><li>Forward secrecy — past sessions protected even if key compromised</li><li>Enhanced Open (OWE) for open networks</li><li>Enterprise mode: 192-bit security suite</li></ul><div class="exam-tip">WPA3-SAE defeats the PMKID attack and offline dictionary attacks. WPA3-Enterprise requires 192-bit AES.</div>`},
'enhanced-open':{title:'Enhanced Open (OWE)',cat:'WPA3',html:`<p>WPA3 feature that provides <strong>opportunistic wireless encryption (OWE)</strong> on open networks — no password required but traffic is still encrypted.</p><h4>How It Works</h4><ul><li>Diffie-Hellman key exchange per session</li><li>No authentication — still open</li><li>Encrypts traffic to prevent passive sniffing</li></ul><div class="exam-tip">Enhanced Open prevents passive sniffing on coffee shop WiFi but does NOT prevent evil twin attacks since there is no AP authentication.</div>`},
'sae':{title:'SAE — Simultaneous Authentication of Equals',cat:'WPA3',html:`<p>WPA3's replacement for the PSK 4-way handshake — uses the <strong>Dragonfly key exchange</strong>.</p><h4>Advantages</h4><ul><li>Resistant to offline dictionary attacks</li><li>No PMKID attack vulnerability</li><li>Forward secrecy per session</li><li>Even weak passwords are protected from offline cracking</li></ul><div class="exam-tip">SAE is the key differentiator of WPA3-Personal. The attacker must attempt authentication online (can be rate-limited) rather than offline.</div>`},
'wpa3-enterprise':{title:'WPA3-Enterprise',cat:'WPA3',html:`<p>WPA3 in enterprise mode with <strong>192-bit security suite</strong> — uses GCMP-256 encryption and SHA-384.</p><div class="exam-tip">WPA3-Enterprise is required for high-security environments (government, defense). It mandates stronger cipher suites than WPA2-Enterprise.</div>`},
'eap-ref':{title:'EAP',cat:'Reference',html:`<div class="ref-note">Base EAP framework covered in Chapter 2. Chapter 4 covers specific EAP methods used in wireless authentication.</div>`},
'peap':{title:'PEAP — Protected EAP',cat:'EAP Methods',html:`<p>Wraps inner EAP authentication inside a <strong>TLS tunnel</strong> — server certificate required, client certificate optional.</p><h4>How It Works</h4><ul><li>Phase 1: TLS tunnel established (server cert)</li><li>Phase 2: Inner auth (MSCHAPv2, GTC) inside tunnel</li><li>Client uses username/password — no client cert</li></ul><div class="exam-tip">PEAP is most common EAP in enterprise WiFi. Server certificate required. Inner method is often MSCHAPv2. Most secure when client validates server cert.</div>`},
'eap-fast':{title:'EAP-FAST — Flexible Auth via Secure Tunneling',cat:'EAP Methods',html:`<p>Cisco-developed EAP method using a <strong>PAC (Protected Access Credential)</strong> instead of certificates to create the tunnel.</p><h4>Phases</h4><ul><li>Phase 0: PAC provisioning (can be automatic)</li><li>Phase 1: Tunnel established using PAC</li><li>Phase 2: Inner authentication</li></ul><div class="exam-tip">EAP-FAST was designed to replace LEAP (Cisco's broken EAP). No certificates required — uses PAC file instead.</div>`},
'eap-tls':{title:'EAP-TLS',cat:'EAP Methods',html:`<p>The <strong>strongest EAP method</strong> — requires certificates on both the client AND server for mutual authentication.</p><h4>Features</h4><ul><li>Mutual certificate authentication</li><li>No passwords — certificates only</li><li>Immune to password-based attacks</li><li>High overhead: PKI required for all clients</li></ul><div class="exam-tip">EAP-TLS = strongest but most complex. Requires a PKI to issue client certs. If you see "most secure EAP" on the exam, the answer is EAP-TLS.</div>`},
'eap-ttls':{title:'EAP-TTLS — Tunneled TLS',cat:'EAP Methods',html:`<p>Like PEAP but allows <strong>legacy inner authentication methods</strong> (PAP, CHAP) inside the TLS tunnel.</p><h4>Advantage over PEAP</h4><ul><li>Supports PAP/CHAP inside tunnel (legacy systems)</li><li>Only server cert required (like PEAP)</li></ul><div class="exam-tip">EAP-TTLS supports older inner auth methods. PEAP typically uses MSCHAPv2. Both only need server certificates.</div>`},
'ptk':{title:'PTK — Pairwise Transient Key',cat:'EAP Methods',html:`<p>A <strong>session-specific encryption key</strong> derived during the WPA2/3 4-way handshake between client and AP.</p><h4>Derivation</h4><ul><li>Derived from PMK + AP nonce + client nonce + MAC addresses</li><li>Unique per session — provides forward secrecy concept</li><li>Contains: KCK, KEK, TK (temporal key)</li></ul><div class="exam-tip">PTK is what actually encrypts the wireless session. A new PTK is generated for every connection, so capturing one session's traffic doesn't expose others.</div>`},
'ieee8021x':{title:'IEEE 802.1X',cat:'802.1X & RADIUS',html:`<p><strong>Port-based network access control</strong> — requires authentication before a port grants full network access.</p><h4>Components</h4><ul><li><strong>Supplicant</strong> — client device requesting access</li><li><strong>Authenticator</strong> — switch/AP enforcing access</li><li><strong>Authentication Server</strong> — RADIUS validates credentials</li></ul><h4>Process</h4><ul><li>Device connects → port blocked (unauth state)</li><li>EAP exchange → RADIUS validates</li><li>Pass: port opened · Fail: port stays blocked</li></ul><div class="exam-tip">802.1X is the standard for both wired and wireless enterprise authentication. It prevents rogue devices from accessing the network even if physically connected.</div>`},
'radius-fed':{title:'RADIUS Federation',cat:'802.1X & RADIUS',html:`<p>A trust relationship allowing <strong>RADIUS servers at different organizations to proxy authentication</strong> requests.</p><h4>Use Case</h4><ul><li>eduroam — university students authenticate at any campus worldwide</li><li>RADIUS proxy forwards to home RADIUS server</li><li>Home server authenticates, response returns</li></ul><div class="exam-tip">RADIUS Federation is used in eduroam and carrier roaming scenarios. The visited network trusts the home network's RADIUS response.</div>`},
'captive-portal':{title:'Captive Portal',cat:'Captive Portal',html:`<p>A web page that <strong>intercepts HTTP requests</strong> and redirects users to an authentication or acceptance page before granting internet access.</p><h4>How It Works</h4><ul><li>Device connects to WiFi — gets IP via DHCP</li><li>All HTTP redirected to portal page</li><li>User accepts terms, pays, or authenticates</li><li>MAC/IP whitelisted, full access granted</li></ul><div class="exam-tip">Captive portals intercept HTTP (not HTTPS). Modern devices detect captive portals via probe requests. Not a substitute for WPA2/3 encryption.</div>`},
'free-internet':{title:'Free Internet (Captive Portal)',cat:'Captive Portal',html:`<p>Captive portal that grants access after <strong>accepting terms of service</strong> — no payment or credentials required.</p><div class="exam-tip">Free captive portals (coffee shops, airports) typically provide no encryption. Use a VPN over free WiFi for security.</div>`},
'paid-internet':{title:'Paid Internet (Captive Portal)',cat:'Captive Portal',html:`<p>Captive portal that <strong>requires payment</strong> (credit card, voucher code) before granting internet access.</p><div class="exam-tip">Hotels and airports often use paid captive portals. Credit card processing on these portals must be secured with TLS — verify the HTTPS lock before entering payment info.</div>`},
'disassoc':{title:'Disassociation Attack',cat:'Wireless Attacks',html:`<p>Sends <strong>spoofed disassociation frames</strong> to force clients off a wireless network — a wireless DoS attack.</p><h4>How It Works</h4><ul><li>802.11 management frames unencrypted in WPA2</li><li>Attacker spoofs AP's MAC, sends deauth/disassoc</li><li>Clients disconnect, often reconnect to evil twin</li></ul><h4>Defense</h4><ul><li>802.11w (Protected Management Frames) encrypts deauth frames</li></ul><div class="exam-tip">802.11w (PMF) is the defense against disassociation attacks. WPA3 mandates 802.11w. Look for PMF or 802.11w as the answer to "prevent deauth attacks."</div>`},
'wps-attack':{title:'WPS Attack (Pixie Dust / PIN Brute-Force)',cat:'Wireless Attacks',html:`<p><strong>WiFi Protected Setup</strong> was designed for easy configuration but has a critical flaw allowing the 8-digit PIN to be cracked.</p><h4>Attack</h4><ul><li>WPS PIN is verified in two 4-digit halves independently</li><li>Reduces brute-force from 100M to 11,000 combinations</li><li>Pixie Dust attack: offline crack in seconds using weak random numbers</li></ul><h4>Defense</h4><ul><li>Disable WPS entirely on all APs</li></ul><div class="exam-tip">WPS should always be disabled. The PIN split validation flaw is unfixable by design. Pixie Dust can crack WPS offline in seconds.</div>`},
'rogue-ap':{title:'Rogue Access Point',cat:'Wireless Attacks',html:`<p>An <strong>unauthorized AP connected to the corporate network</strong> — could be placed by an attacker or a well-meaning employee.</p><h4>Risks</h4><ul><li>Bypasses wired network access controls</li><li>Creates backdoor into corporate network</li><li>May not have proper security configuration</li></ul><h4>Detection</h4><ul><li>Wireless IDS, 802.1X on all wired ports</li><li>Regular site surveys</li></ul><div class="exam-tip">Rogue AP is connected to your network. Evil Twin is outside your network impersonating your AP. These are different attacks.</div>`},
'evil-twin':{title:'Evil Twin',cat:'Wireless Attacks',html:`<p>An attacker-controlled AP that <strong>mimics a legitimate AP's SSID</strong> to trick clients into connecting to it instead.</p><h4>Attack Flow</h4><ul><li>Attacker broadcasts same SSID as target network</li><li>Stronger signal makes clients prefer evil twin</li><li>Disassociation attack forces reconnection</li><li>Attacker performs MitM, captures credentials</li></ul><h4>Defense</h4><ul><li>WPA3-Enterprise (certificate validates server)</li><li>VPN on untrusted networks</li></ul><div class="exam-tip">Evil Twin is outside your network. Rogue AP is inside your network. Evil twin enables MitM attacks — even WPA2-PSK doesn't protect if user connects to the evil twin.</div>`},
'jamming':{title:'Jamming Attack',cat:'Wireless Attacks',html:`<p>Flooding the RF spectrum with <strong>noise to prevent legitimate wireless communication</strong> — wireless DoS.</p><h4>Types</h4><ul><li>Constant jamming — continuous interference</li><li>Reactive jamming — only when traffic detected</li><li>Spot jamming — targets specific frequency</li></ul><div class="exam-tip">Jamming is a physical layer attack — no software defense. Detection via RF spectrum analyzer. Jamming is illegal in most jurisdictions.</div>`},
'iv-attack':{title:'IV Attack — Initialization Vector Attack',cat:'Wireless Attacks',html:`<p>Exploits <strong>repeated IVs in WEP</strong> to statistically recover the encryption key.</p><h4>How It Works</h4><ul><li>WEP uses 24-bit IV — only ~16M unique values</li><li>IVs repeat in busy networks within hours</li><li>Repeated IVs with same key = same keystream</li><li>XOR analysis reveals key material</li></ul><div class="exam-tip">IV attack is why WEP is broken. WPA2/3 use AES which is not vulnerable to IV attacks. If asked why WEP is broken: Initialization Vector weakness.</div>`},
'nfc-attack':{title:'NFC Attack',cat:'Wireless Attacks',html:`<p>Attacks targeting <strong>Near-Field Communication</strong> — the short-range (≤4cm) wireless technology used in contactless payments and access cards.</p><h4>Attack Types</h4><ul><li><strong>Eavesdropping</strong>: capture NFC signal (up to 1m with antenna)</li><li><strong>Relay attack</strong>: extend range of NFC transaction</li><li><strong>Replay attack</strong>: replay captured transaction</li></ul><div class="exam-tip">NFC attacks require physical proximity. Relay attacks can extend effective range to defeat proximity assumption.</div>`},
'rfid':{title:'RFID — Radio Frequency Identification',cat:'Wireless Attacks',html:`<p>Technology using radio waves to <strong>wirelessly identify and track tags</strong> attached to objects, access cards, or assets.</p><h4>Frequencies</h4><ul><li>LF (125 kHz) — older access cards, short range</li><li>HF (13.56 MHz) — smart cards, NFC</li><li>UHF (860–960 MHz) — inventory tracking</li></ul><div class="exam-tip">RFID access cards at LF (125 kHz) have no encryption — trivial to clone. HF (13.56 MHz) smart cards have crypto but can still be attacked.</div>`},
'rfid-clone':{title:'RFID Cloning',cat:'Wireless Attacks',html:`<p>Using a reader device to <strong>capture and duplicate RFID card data</strong> to a blank card for unauthorized access.</p><h4>Process</h4><ul><li>Attacker brings reader close to victim's badge</li><li>Reads unencrypted card data (125 kHz cards)</li><li>Writes data to blank card</li><li>Uses clone to access secured areas</li></ul><div class="exam-tip">125 kHz proximity cards (HID Prox) have no encryption — easily cloned with a $30 device. Upgrade to smart cards (MIFARE/DESFire) or FIDO2 tokens.</div>`},
'sniffing':{title:'Wireless Sniffing',cat:'Wireless Attacks',html:`<p><strong>Capturing wireless frames</strong> using a wireless adapter in monitor mode.</p><h4>What Can Be Captured</h4><ul><li>Unencrypted traffic (HTTP, cleartext protocols)</li><li>WPA2 4-way handshake (for offline cracking)</li><li>SSID probes from client devices</li><li>Management frames</li></ul><div class="exam-tip">Use WPA2/3 Enterprise to prevent credential sniffing. Always use HTTPS/TLS for sensitive data even on encrypted WiFi.</div>`},
'data-exfil':{title:'Data Exfiltration',cat:'Wireless Attacks',html:`<p>Unauthorized transfer of data <strong>out of an organization via wireless</strong> — can be intentional (insider) or attacker-initiated.</p><h4>Wireless Methods</h4><ul><li>Connect personal device to corporate WiFi, copy files</li><li>Use rogue AP as covert exit channel</li><li>Bluetooth file transfer</li></ul><div class="exam-tip">DLP (Data Loss Prevention), 802.1X, and network monitoring detect data exfiltration attempts.</div>`},
'ddos':{title:'DDoS — Distributed Denial of Service',cat:'Wireless Attacks',html:`<p>A <strong>coordinated flood of traffic from many sources</strong> overwhelming a network or service.</p><h4>Wireless DDoS Types</h4><ul><li>Deauthentication flood (layer 2)</li><li>RF jamming (layer 1)</li><li>Association flood (exhaust AP connection table)</li></ul><div class="exam-tip">Wireless DDoS at L2 is defeated by 802.11w (PMF). RF jamming requires physical location and removal of the jammer.</div>`},
'wireless-replay':{title:'Wireless Replay Attack',cat:'Wireless Attacks',html:`<p><strong>Capturing legitimate wireless frames and retransmitting</strong> them to replay a valid transaction.</p><h4>Example</h4><ul><li>Capture authentication exchange</li><li>Replay it later to re-authenticate without credentials</li></ul><h4>Defense</h4><ul><li>Nonces and timestamps in WPA2/3 handshake prevent replay</li><li>Per-session keys (PTK) make replayed frames invalid</li></ul><div class="exam-tip">WPA2/3 uses nonces in the 4-way handshake specifically to prevent replay attacks. Each session generates unique keys.</div>`},
'bluetooth':{title:'Bluetooth',cat:'Bluetooth Attacks',html:`<p>Short-range wireless technology (≤100m) operating at <strong>2.4 GHz using frequency hopping spread spectrum</strong>.</p><h4>Versions</h4><ul><li>Bluetooth Classic — audio, file transfer</li><li>BLE (Bluetooth Low Energy) — IoT, beacons</li></ul><div class="exam-tip">Bluetooth pairing creates a shared key. "Discoverable" mode is a security risk — set devices to non-discoverable when not pairing.</div>`},
'bluejacking':{title:'Bluejacking',cat:'Bluetooth Attacks',html:`<p>Sending <strong>unsolicited messages</strong> to nearby Bluetooth devices — mostly annoying, not directly harmful.</p><div class="exam-tip">Bluejacking = messages only. Bluesnarfing = data theft. Bluebugging = full control. Know the severity order for the exam.</div>`},
'bluesnarfing':{title:'Bluesnarfing',cat:'Bluetooth Attacks',html:`<p><strong>Unauthorized access to data</strong> on a Bluetooth device — contacts, messages, calendar, files.</p><h4>Requirements</h4><ul><li>Device in discoverable mode</li><li>Exploits OBEX push vulnerabilities</li><li>Does not require pairing</li></ul><div class="exam-tip">Bluesnarfing steals data without user interaction or pairing. Keep Bluetooth off when not in use and set to non-discoverable.</div>`},
'bluebugging':{title:'Bluebugging',cat:'Bluetooth Attacks',html:`<p>The most severe Bluetooth attack — attacker gains <strong>full control of the victim's device</strong> including calls, messages, and microphone.</p><div class="exam-tip">Severity: Bluejacking (annoyance) &lt; Bluesnarfing (data theft) &lt; Bluebugging (full control). Bluebugging is the most dangerous.</div>`},
'war-drive':{title:'War Driving',cat:'War Driving & Audit',html:`<p><strong>Driving through an area with a WiFi-enabled device</strong> to discover and map wireless networks.</p><h4>Tools</h4><ul><li>Kismet, inSSIDer, NetStumbler</li><li>GPS for location mapping</li><li>Directional antenna to increase range</li></ul><div class="exam-tip">War driving is passive scanning — legal in most jurisdictions (receiving broadcasts). Connecting to networks without authorization is illegal.</div>`},
'war-fly':{title:'War Flying',cat:'War Driving & Audit',html:`<p>Same as war driving but conducted from a <strong>drone or aircraft</strong> — covers larger areas.</p><div class="exam-tip">War flying covers more area than war driving. Organizations with outdoor facilities must consider RF leakage that's visible from above.</div>`},
'wireless-audit':{title:'Wireless Audit',cat:'War Driving & Audit',html:`<p>An <strong>authorized assessment of wireless security</strong> — finds rogue APs, weak configurations, and coverage issues.</p><h4>Includes</h4><ul><li>Passive scanning for all SSIDs and APs</li><li>Testing authentication strength</li><li>Checking for rogue APs and evil twins</li><li>Verifying 802.11w / WPA3 compliance</li></ul><div class="exam-tip">Wireless audits are authorized (unlike war driving). Always get written permission before testing. Tools are the same as attacker tools.</div>`},
'vpn-ref':{title:'VPN',cat:'Reference',html:`<div class="ref-note">Base VPN concept covered in Chapter 3. This chapter covers VPN concentrators, tunnel vs transport modes, and remote access deployment models.</div>`},
'vpn-conc':{title:'VPN Concentrator',cat:'VPN Types',html:`<p>A dedicated device that <strong>terminates large numbers of VPN tunnels</strong> — handles encryption/decryption at scale.</p><h4>Features</h4><ul><li>Dedicated crypto hardware acceleration</li><li>Manages authentication and key exchange</li><li>Load balances VPN sessions</li><li>Often integrated into firewall platforms</li></ul><div class="exam-tip">VPN concentrators are used for remote access VPNs with many simultaneous users. Without a concentrator, routers handle tunnels — less scalable.</div>`},
'remote-vpn':{title:'Remote Access VPN',cat:'VPN Types',html:`<p>Connects <strong>individual users to a corporate network</strong> over the internet — client-to-site.</p><h4>Use Case</h4><ul><li>Work-from-home employees</li><li>Road warriors accessing internal resources</li><li>Client software installed on endpoint</li></ul><div class="exam-tip">Remote access VPN = client-to-site. Site-to-site VPN = gateway-to-gateway. Remote access requires VPN client software on the device.</div>`},
'site-vpn':{title:'Site-to-Site VPN',cat:'VPN Types',html:`<p>Connects <strong>two entire networks together</strong> — gateway-to-gateway, transparent to end users.</p><h4>Use Case</h4><ul><li>Branch office to HQ connectivity</li><li>No VPN client needed on workstations</li><li>Always-on connection between sites</li></ul><div class="exam-tip">Site-to-site VPN is transparent to users — they don't need client software. The gateways handle all encryption.</div>`},
'always-on-vpn':{title:'Always-On VPN',cat:'VPN Types',html:`<p>VPN that <strong>automatically connects whenever the device is not on the trusted corporate network</strong> — no user action required.</p><h4>Benefits</h4><ul><li>Ensures all traffic is encrypted off-premises</li><li>Enforces security policy consistently</li><li>Used with MDM/UEM platforms</li></ul><div class="exam-tip">Always-on VPN is common in zero-trust implementations. Users cannot bypass it — all off-network traffic is tunneled.</div>`},
'split-tunnel':{title:'Split Tunnel VPN',cat:'VPN Types',html:`<p>Only <strong>corporate-bound traffic goes through the VPN</strong> — internet traffic goes directly.</p><h4>Pros / Cons</h4><ul><li>Less bandwidth usage on VPN gateway</li><li>Better performance for internet browsing</li><li>Risk: internet traffic unmonitored by corporate security</li></ul><div class="exam-tip">Split tunneling is a security risk — user can access the internet directly without corporate filtering. Full tunnel is more secure but uses more bandwidth.</div>`},
'full-tunnel':{title:'Full Tunnel VPN',cat:'VPN Types',html:`<p><strong>All traffic routes through the VPN</strong> — including internet browsing.</p><h4>Pros / Cons</h4><ul><li>Full corporate security visibility and filtering</li><li>Higher bandwidth usage on VPN gateway</li><li>Can slow internet performance</li></ul><div class="exam-tip">Full tunnel = more secure. Split tunnel = better performance. Security-conscious orgs mandate full tunnel especially for privileged users.</div>`},
'html5-vpn':{title:'HTML5 VPN Portal (Clientless VPN)',cat:'VPN Types',html:`<p>Browser-based VPN access — <strong>no VPN client software required</strong>. Uses HTML5/JavaScript in the browser.</p><h4>How It Works</h4><ul><li>User navigates to HTTPS portal</li><li>Portal proxies access to internal resources</li><li>Works from any device with a browser</li></ul><div class="exam-tip">HTML5/clientless VPN is ideal for contractor/BYOD access where installing a client is impractical. Limited to web-based resources unless full proxying is configured.</div>`},
'tunnel-mode':{title:'Tunnel Mode (IPsec)',cat:'VPN Protocols',html:`<p>IPsec mode that <strong>encapsulates the entire original IP packet</strong> — new IP header added.</p><h4>Use Case</h4><ul><li>Site-to-site VPNs — gateways encapsulate packets</li><li>Hides original source/destination IPs</li><li>Original packet fully encrypted</li></ul><div class="exam-tip">Tunnel mode = entire packet encrypted + new header. Transport mode = only payload encrypted, original header intact. Tunnel mode used for gateway-to-gateway VPNs.</div>`},
'transport-mode':{title:'Transport Mode (IPsec)',cat:'VPN Protocols',html:`<p>IPsec mode that <strong>encrypts only the payload</strong> — original IP header remains intact.</p><h4>Use Case</h4><ul><li>Host-to-host encryption</li><li>End-to-end between two specific hosts</li><li>Original IP header visible (routing still works)</li></ul><div class="exam-tip">Transport mode preserves original IP header. Used for host-to-host (not gateway). Less overhead than tunnel mode.</div>`},
'esp':{title:'ESP — Encapsulating Security Payload (Port 50)',cat:'VPN Protocols',html:`<p>IPsec protocol that provides <strong>encryption, authentication, and integrity</strong> for IP packets.</p><h4>Features</h4><ul><li>Protocol number: <code>50</code></li><li>Provides confidentiality (encryption)</li><li>Also provides authentication and integrity</li><li>Most commonly used IPsec protocol</li></ul><div class="exam-tip">ESP (50) = encryption + auth. AH (51) = auth only, no encryption. ESP is preferred because it provides confidentiality. AH is rarely used alone.</div>`},
'ah':{title:'AH — Authentication Header (Port 51)',cat:'VPN Protocols',html:`<p>IPsec protocol providing <strong>authentication and integrity only — no encryption</strong>.</p><h4>Features</h4><ul><li>Protocol number: <code>51</code></li><li>Signs entire packet including IP header</li><li>No encryption — payload is cleartext</li><li>Incompatible with NAT (signs headers that NAT changes)</li></ul><div class="exam-tip">AH (51) = integrity/auth, NO encryption. ESP (50) = encryption + auth. AH breaks with NAT. For the exam: ESP is almost always the right choice.</div>`},
'ike':{title:'IKE — Internet Key Exchange',cat:'VPN Protocols',html:`<p>Protocol used to <strong>negotiate and establish IPsec security associations (SAs)</strong> and exchange keys.</p><h4>Versions</h4><ul><li><strong>IKEv1</strong> — two phases, older, more complex</li><li><strong>IKEv2</strong> — simpler, more reliable, supports MOBIKE</li></ul><h4>Ports</h4><ul><li>UDP 500 — IKE negotiation</li><li>UDP 4500 — NAT traversal</li></ul><div class="exam-tip">IKE runs on UDP 500. IKEv2 is preferred — it handles NAT traversal and mobile devices better than IKEv1.</div>`},
'sstp':{title:'SSTP — Secure Socket Tunneling Protocol',cat:'VPN Protocols',html:`<p>Microsoft VPN protocol that <strong>tunnels PPP traffic over HTTPS (port 443)</strong>.</p><h4>Advantages</h4><ul><li>Uses port 443 — passes through most firewalls</li><li>SSL/TLS encryption</li><li>Native Windows support</li></ul><div class="exam-tip">SSTP uses port 443 — nearly impossible to block without breaking HTTPS. Useful when traditional VPN ports (UDP 500) are blocked.</div>`},
'l2tp':{title:'L2TP — Layer 2 Tunneling Protocol',cat:'VPN Protocols',html:`<p>A tunneling protocol that <strong>provides no encryption itself</strong> — always paired with IPsec.</p><h4>L2TP/IPsec</h4><ul><li>L2TP creates the tunnel</li><li>IPsec provides encryption and authentication</li><li>Uses UDP 1701 (L2TP) inside IPsec</li></ul><div class="exam-tip">L2TP alone has no security. L2TP/IPsec is a common combination. The exam may ask: "L2TP provides no encryption — it relies on IPsec."</div>`},
'nac':{title:'NAC — Network Access Control',cat:'NAC',html:`<p>A system that <strong>evaluates device health/posture</strong> before granting network access — enforces security policy at the point of connection.</p><h4>Posture Checks</h4><ul><li>OS patched and up to date?</li><li>Antivirus running and current?</li><li>Encryption enabled?</li><li>Corporate certificate present?</li></ul><h4>Outcomes</h4><ul><li>Pass: full network access</li><li>Fail: quarantine VLAN for remediation</li></ul><div class="exam-tip">NAC enforces posture before access. Quarantine VLAN is key — failed devices get limited network to self-remediate, then re-checked.</div>`},
'agent-nac':{title:'Agent-Based NAC',cat:'NAC',html:`<p>NAC using a <strong>software agent installed on the endpoint</strong> that reports posture to the NAC system.</p><h4>Advantages</h4><ul><li>Deep visibility into device state</li><li>Can check running processes, registry, file hashes</li><li>Persistent agent or dissolvable (web-based)</li></ul><div class="exam-tip">Agent-based NAC has more visibility but requires software on every device. Agentless is better for BYOD and guest devices.</div>`},
'agentless-nac':{title:'Agentless NAC',cat:'NAC',html:`<p>NAC that uses <strong>network-side scanning</strong> to assess device posture without installing software on the device.</p><h4>Methods</h4><ul><li>Network scan for open ports/OS fingerprint</li><li>AD authentication check</li><li>DHCP fingerprinting</li></ul><div class="exam-tip">Agentless NAC is weaker but works for BYOD, guest devices, and IoT. No software to manage but limited visibility compared to agents.</div>`},
'pap':{title:'PAP — Password Authentication Protocol',cat:'Auth Protocols',html:`<p>The <strong>simplest and most insecure</strong> PPP authentication protocol — sends passwords in cleartext.</p><div class="exam-tip">PAP = cleartext passwords. Never use. Only referenced in the exam as an example of insecure legacy authentication. CHAP replaced it.</div>`},
'ppp':{title:'PPP — Point-to-Point Protocol',cat:'Auth Protocols',html:`<p>A data link layer protocol for <strong>direct connections between two nodes</strong> — historically used for dial-up. Carries authentication sub-protocols.</p><div class="exam-tip">PPP is the carrier for PAP and CHAP. Still relevant as L2TP uses PPP internally.</div>`},
'chap':{title:'CHAP — Challenge Handshake Auth Protocol',cat:'Auth Protocols',html:`<p>PPP authentication using a <strong>3-way challenge-response</strong> — password never sent over the wire.</p><h4>Process</h4><ul><li>Server sends random challenge</li><li>Client: MD5(challenge + password)</li><li>Server independently computes same hash</li><li>If match: authenticated</li></ul><div class="exam-tip">CHAP prevents replay attacks via random challenges. MS-CHAPv2 is the Windows version. CHAP is still weak (MD5) — use stronger EAP methods for WiFi.</div>`},
'tacacs':{title:'TACACS+ — Terminal Access Controller Access Control System+',cat:'Auth Protocols',html:`<p>Cisco's AAA protocol — <strong>encrypts the entire payload</strong> (unlike RADIUS which only encrypts the password).</p><h4>TACACS+ vs RADIUS</h4><ul><li>TACACS+: TCP 49, full encryption, separates AAA</li><li>RADIUS: UDP 1812/1813, encrypts password only, combines AuthN+AuthZ</li><li>TACACS+: better for device administration (routers/switches)</li><li>RADIUS: better for user authentication (WiFi, VPN)</li></ul><div class="exam-tip">TACACS+ encrypts everything — RADIUS only encrypts the password. TACACS+ uses TCP — RADIUS uses UDP. TACACS+ is preferred for network device management.</div>`},
'net-diameter':{title:'Diameter Protocol',cat:'Auth Protocols',html:`<p>The <strong>successor to RADIUS</strong> — designed to overcome RADIUS limitations for modern networks.</p><h4>Improvements over RADIUS</h4><ul><li>Uses TCP/SCTP (reliable) vs UDP</li><li>Peer-to-peer (not client-server)</li><li>Better failover and capability negotiation</li><li>Used in 4G/5G mobile networks (EPS)</li></ul><div class="exam-tip">Diameter = RADIUS successor. Used in mobile carrier networks (LTE/5G). The name is a math pun: Diameter is twice the RADIUS.</div>`},
'nat-ref':{title:'NAT',cat:'Reference',html:`<div class="ref-note">Covered fully in Chapter 3 (Network Address Translation). Referenced here as part of wireless network infrastructure.</div>`},
'pat-ref':{title:'PAT',cat:'Reference',html:`<div class="ref-note">Covered fully in Chapter 3 (Port Address Translation). Referenced here as part of wireless network infrastructure.</div>`},
'dhcp-ref':{title:'DHCP',cat:'Reference',html:`<div class="ref-note">Covered fully in Chapter 3 (Dynamic Host Configuration Protocol). Referenced here as part of wireless network infrastructure.</div>`},
'radius-ref2':{title:'RADIUS',cat:'Reference',html:`<div class="ref-note">Covered in Chapter 2 and Chapter 3. In Chapter 4, RADIUS authenticates wireless enterprise users via 802.1X and EAP.</div>`},
'eap-ref2':{title:'EAP',cat:'Reference',html:`<div class="ref-note">Base EAP framework covered in Chapter 2. Chapter 4 covers specific wireless EAP methods: PEAP, EAP-TLS, EAP-TTLS, EAP-FAST.</div>`},
};

const CATEGORIES=[
  {id:'ids',     label:'IDS / IPS',             color:'#1abc9c', nodes:['hids','nids','sig-ids','trend-ids','zero-day','aggregator','ids-ref','port-mirror','port-tap']},
  {id:'deception',label:'Deception Tech',        color:'#9b59b6', nodes:['honeypot','honeynet','honeyfile','honeytoken','apt']},
  {id:'wireless', label:'Wireless Fundamentals', color:'#3498db', nodes:['wlan','ap','ssid','mac-addr','mac-filter','net-bands','wifi-std','nat-ref','pat-ref','dhcp-ref']},
  {id:'survey',   label:'Site Survey',           color:'#06b6d4', nodes:['site-survey','wifi-analyzer','heat-map','wireless-footprint','omni-antenna','dir-antenna']},
  {id:'wep-wpa2', label:'WEP & WPA2',            color:'#e67e22', nodes:['wep','wpa','wpa2','psk','open-mode','enterprise-mode','radius-ref','shared-secret']},
  {id:'wpa3',     label:'WPA3',                  color:'#2ecc71', nodes:['wpa3','enhanced-open','sae','wpa3-enterprise']},
  {id:'eap',      label:'EAP Methods',           color:'#8b5cf6', nodes:['eap-ref','peap','eap-fast','eap-tls','eap-ttls','ptk','ieee8021x','radius-fed']},
  {id:'attacks',  label:'Wireless Attacks',      color:'#e74c3c', nodes:['disassoc','wps-attack','rogue-ap','evil-twin','jamming','iv-attack','nfc-attack','rfid','rfid-clone','sniffing','data-exfil','ddos','wireless-replay']},
  {id:'bt',       label:'Bluetooth',             color:'#3b82f6', nodes:['bluetooth','bluejacking','bluesnarfing','bluebugging','war-drive','war-fly','wireless-audit']},
  {id:'vpn',      label:'VPN',                   color:'#2ecc71', nodes:['vpn-ref','vpn-conc','remote-vpn','site-vpn','always-on-vpn','split-tunnel','full-tunnel','html5-vpn','tunnel-mode','transport-mode','esp','ah','ike','sstp','l2tp']},
  {id:'nac',      label:'NAC & Auth Protocols',  color:'#f97316', nodes:['nac','agent-nac','agentless-nac','pap','ppp','chap','tacacs','net-diameter','captive-portal','free-internet','paid-internet','radius-ref2','eap-ref2']},
];

const NODE_CAT_MAP={};
CATEGORIES.forEach(c=>c.nodes.forEach(n=>{if(!NODE_CAT_MAP[n])NODE_CAT_MAP[n]=[];NODE_CAT_MAP[n].push(c.id);}));

(function buildSidebar(){
  const list=document.getElementById('cat-list');
  CATEGORIES.forEach(c=>{
    const btn=document.createElement('button');btn.className='cat-btn';btn.dataset.catId=c.id;
    btn.innerHTML=`<span class="cat-dot" style="background:${c.color}"></span><span>${c.label}</span>`;
    btn.addEventListener('click',()=>activeCat===c.id?clearFilter():applyFilter(c.id));
    list.appendChild(btn);
  });
})();

let activeCat=null;
function applyFilter(catId){
  activeCat=catId;const cat=CATEGORIES.find(c=>c.id===catId);const matchSet=new Set(cat.nodes);
  document.querySelectorAll('.node[data-node-id]').forEach(n=>{n.classList.remove('cat-match','cat-dim');n.classList.add(matchSet.has(n.dataset.nodeId)?'cat-match':'cat-dim');});
  document.querySelectorAll('.zone').forEach(z=>{const ns=z.querySelectorAll('.node[data-node-id]');z.classList.toggle('zone-all-dim',[...ns].every(n=>n.classList.contains('cat-dim'))&&ns.length>0);});
  document.body.classList.add('cat-filtered');
  document.querySelectorAll('.cat-btn').forEach(b=>b.classList.toggle('active',b.dataset.catId===catId));
  const banner=document.getElementById('filter-banner');banner.style.display='block';banner.style.color=cat.color;banner.style.borderColor=cat.color;
  banner.innerHTML=`${cat.label}<br><span style="opacity:.55;font-size:8px">click to clear</span>`;banner.onclick=clearFilter;
  document.getElementById('clear-btn').style.display='block';
  if(gGraphActive&&gGraphInited)applyGraphFilter(catId);
}
function clearFilter(){
  activeCat=null;document.body.classList.remove('cat-filtered');
  document.querySelectorAll('.node').forEach(n=>n.classList.remove('cat-match','cat-dim'));
  document.querySelectorAll('.zone').forEach(z=>z.classList.remove('zone-all-dim'));
  document.querySelectorAll('.cat-btn').forEach(b=>b.classList.remove('active'));
  document.getElementById('filter-banner').style.display='none';document.getElementById('clear-btn').style.display='none';
  if(gGraphActive&&gGraphInited)clearGraphFilter();
}

let selectedNode=null;
function openDetail(id){
  const d=NODE_DATA[id];if(!d)return;
  if(selectedNode)selectedNode.classList.remove('selected');
  const el=document.querySelector(`.node[data-node-id="${id}"]`);
  if(el){el.classList.add('selected');selectedNode=el;}
  document.getElementById('detail-title').textContent=d.title;
  document.getElementById('detail-category').textContent=d.cat;
  document.getElementById('detail-body').innerHTML=d.html;
  document.getElementById('detail-panel').classList.remove('collapsed');
  document.body.classList.add('detail-open');
}
function closeDetail(){
  document.getElementById('detail-panel').classList.add('collapsed');document.body.classList.remove('detail-open');
  if(selectedNode){selectedNode.classList.remove('selected');selectedNode=null;}
}
/* ═══ GRAPH ═══ */
function gn(id,label,color,nodeId,x,y){return{id,label,color,nodeId:nodeId||null,x,y,vx:0,vy:0,r:20,pinned:false}}
function ge(s,t,type,label){return{s,t,type:type||'relates',label:label||null}}
const GNODES=[
  gn('cat-ids',    'IDS / IPS',        '#1abc9c',null,    0,    0),
  gn('cat-dec',    'Deception',        '#9b59b6',null, -340, -200),
  gn('cat-wifi',   'Wireless\nFundamentals','#3498db',null,  340, -200),
  gn('cat-survey', 'Site Survey',      '#06b6d4',null,  580, -100),
  gn('cat-wpa',    'WEP / WPA2',       '#e67e22',null,  340,  200),
  gn('cat-wpa3',   'WPA3',             '#2ecc71',null,  580,  300),
  gn('cat-eap',    'EAP / 802.1X',     '#8b5cf6',null,  200,  400),
  gn('cat-atk',    'Wireless\nAttacks','#e74c3c',null,    0, -350),
  gn('cat-bt',     'Bluetooth\n& War', '#3b82f6',null, -340,  200),
  gn('cat-vpn',    'VPN',              '#2ecc71',null, -340,  450),
  gn('cat-nac',    'NAC & Auth',       '#f97316',null,  200, -200),
  // IDS
  gn('hids',    'HIDS',         '#1abc9c','hids',    -140,  -60),
  gn('nids',    'NIDS',         '#1abc9c','nids',     -80,   80),
  gn('sig-ids', 'Signature IDS','#1abc9c','sig-ids',   80,   80),
  gn('trend-ids','Trend IDS',   '#1abc9c','trend-ids', 140,  -60),
  gn('zero-day','Zero-Day',     '#e67e22','zero-day',   60, -100),
  gn('aggregator','Aggregator', '#3498db','aggregator',-60,  140),
  gn('port-mirror','Port Mirror','#3498db','port-mirror',-180,80),
  gn('port-tap','Port Tap',     '#3498db','port-tap',  -180, 160),
  // Deception
  gn('honeypot','Honeypot',     '#9b59b6','honeypot',  -460,-180),
  gn('honeynet','Honeynet',     '#9b59b6','honeynet',  -420,-280),
  gn('honeyfile','Honey File',  '#9b59b6','honeyfile', -320,-320),
  gn('honeytoken','Honey Token','#9b59b6','honeytoken',-260,-240),
  gn('apt',     'APT',          '#e74c3c','apt',       -400,-140),
  // Wireless
  gn('wlan',    'WLAN',         '#3498db','wlan',       460,-220),
  gn('ap',      'AP',           '#3498db','ap',         560,-180),
  gn('ssid',    'SSID',         '#3498db','ssid',       420,-300),
  gn('mac-addr','MAC Addr',     '#3498db','mac-addr',   520,-300),
  gn('mac-filter','MAC Filter', '#e67e22','mac-filter', 600,-240),
  gn('net-bands','Net Bands',   '#3498db','net-bands',  420,-140),
  gn('wifi-std','WiFi Stds',    '#3498db','wifi-std',   500,-100),
  // Survey
  gn('site-survey','Site Survey','#06b6d4','site-survey',700,-160),
  gn('wifi-analyzer','WiFi Analyzer','#06b6d4','wifi-analyzer',760,-80),
  gn('heat-map','Heat Map',     '#06b6d4','heat-map',   760,-200),
  gn('wireless-footprint','Footprint','#06b6d4','wireless-footprint',700,-280),
  gn('omni-antenna','Omni\nAntenna','#3498db','omni-antenna',680,-360),
  gn('dir-antenna','Dir\nAntenna','#3498db','dir-antenna',780,-300),
  // WPA2
  gn('wep',     'WEP',          '#e74c3c','wep',         260,  140),
  gn('wpa',     'WPA/TKIP',     '#e67e22','wpa',         300,  260),
  gn('wpa2',    'WPA2',         '#2ecc71','wpa2',        460,  200),
  gn('psk',     'PSK',          '#2ecc71','psk',         560,  140),
  gn('open-mode','Open Mode',   '#3498db','open-mode',   440,  300),
  gn('enterprise-mode','Enterprise','#3498db','enterprise-mode',560,260),
  gn('shared-secret','Shared\nSecret','#3498db','shared-secret',640,200),
  // WPA3
  gn('wpa3',    'WPA3',         '#2ecc71','wpa3',        680,  320),
  gn('sae',     'SAE',          '#2ecc71','sae',         760,  260),
  gn('enhanced-open','Enhanced\nOpen','#1abc9c','enhanced-open',760,380),
  gn('wpa3-enterprise','WPA3-Ent','#2ecc71','wpa3-enterprise',700,440),
  // EAP
  gn('peap',    'PEAP',         '#8b5cf6','peap',        280,  480),
  gn('eap-fast','EAP-FAST',     '#8b5cf6','eap-fast',    160,  520),
  gn('eap-tls', 'EAP-TLS',      '#2ecc71','eap-tls',     380,  520),
  gn('eap-ttls','EAP-TTLS',     '#8b5cf6','eap-ttls',    460,  460),
  gn('ptk',     'PTK',          '#1abc9c','ptk',         520,  380),
  gn('ieee8021x','802.1X',      '#1abc9c','ieee8021x',   200,  300),
  gn('radius-fed','RADIUS Fed', '#3498db','radius-fed',  200,  200),
  gn('captive-portal','Captive\nPortal','#3498db','captive-portal',100,280),
  // Attacks
  gn('disassoc','Disassoc\nAttack','#e74c3c','disassoc', -180,-300),
  gn('wps-attack','WPS Attack', '#e74c3c','wps-attack',  -60,-420),
  gn('rogue-ap','Rogue AP',     '#e74c3c','rogue-ap',     60,-420),
  gn('evil-twin','Evil Twin',   '#e74c3c','evil-twin',   180,-380),
  gn('jamming', 'Jamming',      '#e74c3c','jamming',     -80,-480),
  gn('iv-attack','IV Attack',   '#e74c3c','iv-attack',   -200,-400),
  gn('nfc-attack','NFC Attack', '#e67e22','nfc-attack',  220,-460),
  gn('rfid',    'RFID',         '#e67e22','rfid',        300,-380),
  gn('rfid-clone','RFID Clone', '#e74c3c','rfid-clone',  300,-280),
  gn('sniffing','Sniffing',     '#e74c3c','sniffing',   -300,-480),
  gn('ddos',    'DDoS',         '#e74c3c','ddos',        -60,-340),
  gn('wireless-replay','Replay','#e74c3c','wireless-replay',120,-300),
  gn('data-exfil','Data Exfil', '#e74c3c','data-exfil', -160,-480),
  // Bluetooth
  gn('bluetooth','Bluetooth',   '#3b82f6','bluetooth',  -460,  180),
  gn('bluejacking','Bluejacking','#e67e22','bluejacking',-560,  120),
  gn('bluesnarfing','Bluesnarfing','#e74c3c','bluesnarfing',-580,220),
  gn('bluebugging','Bluebugging','#e74c3c','bluebugging',-520,  300),
  gn('war-drive','War Driving', '#e67e22','war-drive',  -480,  340),
  gn('war-fly', 'War Flying',   '#e67e22','war-fly',    -420,  420),
  gn('wireless-audit','Wireless\nAudit','#1abc9c','wireless-audit',-340,360),
  // VPN
  gn('vpn-conc','VPN Conc.',    '#2ecc71','vpn-conc',   -460,  440),
  gn('remote-vpn','Remote\nVPN','#2ecc71','remote-vpn', -540,  520),
  gn('site-vpn','Site-to-Site\nVPN','#2ecc71','site-vpn',-420,560),
  gn('always-on-vpn','Always-On\nVPN','#1abc9c','always-on-vpn',-300,540),
  gn('split-tunnel','Split\nTunnel','#3498db','split-tunnel',-200,580),
  gn('full-tunnel','Full\nTunnel','#3498db','full-tunnel',-100,560),
  gn('html5-vpn','HTML5 VPN',   '#9b59b6','html5-vpn',  -200,  480),
  gn('tunnel-mode','Tunnel\nMode','#3498db','tunnel-mode',-580,380),
  gn('transport-mode','Transport\nMode','#3498db','transport-mode',-620,460),
  gn('esp',     'ESP (50)',      '#2ecc71','esp',        -640,  300),
  gn('ah',      'AH (51)',       '#1abc9c','ah',         -700,  380),
  gn('ike',     'IKE',           '#2ecc71','ike',        -660,  220),
  gn('sstp',    'SSTP',          '#3498db','sstp',       -560,  260),
  gn('l2tp',    'L2TP',          '#3498db','l2tp',       -580,  180),
  // NAC
  gn('nac',     'NAC',           '#f97316','nac',          80, -200),
  gn('agent-nac','Agent NAC',    '#2ecc71','agent-nac',   180, -140),
  gn('agentless-nac','Agentless\nNAC','#3498db','agentless-nac',180,-260),
  gn('pap',     'PAP',           '#e74c3c','pap',         300, -160),
  gn('ppp',     'PPP',           '#95a5a6','ppp',         320, -80),
  gn('chap',    'CHAP',          '#e67e22','chap',        280, -260),
  gn('tacacs',  'TACACS+',       '#1abc9c','tacacs',      120, -120),
  gn('net-diameter','Diameter',  '#3498db','net-diameter', 80, -100),
];
const GEDGES=[
  // category membership
  ge('cat-ids','hids','member'),ge('cat-ids','nids','member'),ge('cat-ids','sig-ids','member'),ge('cat-ids','trend-ids','member'),ge('cat-ids','zero-day','member'),ge('cat-ids','aggregator','member'),ge('cat-ids','port-mirror','member'),ge('cat-ids','port-tap','member'),
  ge('cat-dec','honeypot','member'),ge('cat-dec','honeynet','member'),ge('cat-dec','honeyfile','member'),ge('cat-dec','honeytoken','member'),ge('cat-dec','apt','member'),
  ge('cat-wifi','wlan','member'),ge('cat-wifi','ap','member'),ge('cat-wifi','ssid','member'),ge('cat-wifi','mac-addr','member'),ge('cat-wifi','mac-filter','member'),ge('cat-wifi','net-bands','member'),ge('cat-wifi','wifi-std','member'),
  ge('cat-survey','site-survey','member'),ge('cat-survey','wifi-analyzer','member'),ge('cat-survey','heat-map','member'),ge('cat-survey','wireless-footprint','member'),ge('cat-survey','omni-antenna','member'),ge('cat-survey','dir-antenna','member'),
  ge('cat-wpa','wep','member'),ge('cat-wpa','wpa','member'),ge('cat-wpa','wpa2','member'),ge('cat-wpa','psk','member'),ge('cat-wpa','open-mode','member'),ge('cat-wpa','enterprise-mode','member'),ge('cat-wpa','shared-secret','member'),
  ge('cat-wpa3','wpa3','member'),ge('cat-wpa3','sae','member'),ge('cat-wpa3','enhanced-open','member'),ge('cat-wpa3','wpa3-enterprise','member'),
  ge('cat-eap','peap','member'),ge('cat-eap','eap-fast','member'),ge('cat-eap','eap-tls','member'),ge('cat-eap','eap-ttls','member'),ge('cat-eap','ptk','member'),ge('cat-eap','ieee8021x','member'),ge('cat-eap','radius-fed','member'),ge('cat-eap','captive-portal','member'),
  ge('cat-atk','disassoc','member'),ge('cat-atk','wps-attack','member'),ge('cat-atk','rogue-ap','member'),ge('cat-atk','evil-twin','member'),ge('cat-atk','jamming','member'),ge('cat-atk','iv-attack','member'),ge('cat-atk','nfc-attack','member'),ge('cat-atk','rfid','member'),ge('cat-atk','rfid-clone','member'),ge('cat-atk','sniffing','member'),ge('cat-atk','ddos','member'),ge('cat-atk','wireless-replay','member'),ge('cat-atk','data-exfil','member'),
  ge('cat-bt','bluetooth','member'),ge('cat-bt','bluejacking','member'),ge('cat-bt','bluesnarfing','member'),ge('cat-bt','bluebugging','member'),ge('cat-bt','war-drive','member'),ge('cat-bt','war-fly','member'),ge('cat-bt','wireless-audit','member'),
  ge('cat-vpn','vpn-conc','member'),ge('cat-vpn','remote-vpn','member'),ge('cat-vpn','site-vpn','member'),ge('cat-vpn','always-on-vpn','member'),ge('cat-vpn','split-tunnel','member'),ge('cat-vpn','full-tunnel','member'),ge('cat-vpn','html5-vpn','member'),ge('cat-vpn','tunnel-mode','member'),ge('cat-vpn','transport-mode','member'),ge('cat-vpn','esp','member'),ge('cat-vpn','ah','member'),ge('cat-vpn','ike','member'),ge('cat-vpn','sstp','member'),ge('cat-vpn','l2tp','member'),
  ge('cat-nac','nac','member'),ge('cat-nac','agent-nac','member'),ge('cat-nac','agentless-nac','member'),ge('cat-nac','pap','member'),ge('cat-nac','ppp','member'),ge('cat-nac','chap','member'),ge('cat-nac','tacacs','member'),ge('cat-nac','net-diameter','member'),
  // semantic
  ge('nids','port-mirror','uses','SPAN copy'),ge('nids','port-tap','uses','hardware tap'),
  ge('sig-ids','zero-day','misses','blind to'),ge('trend-ids','zero-day','detects','behavior change'),
  ge('nids','aggregator','sends-to','alert data'),ge('hids','aggregator','sends-to','host events'),
  ge('apt','zero-day','exploits','unknown vuln'),ge('apt','honeypot','caught-by','deception'),
  ge('honeynet','honeypot','contains','multiple'),
  ge('wpa2','psk','personal-mode','passphrase'),ge('wpa2','enterprise-mode','enterprise-mode','802.1X'),
  ge('enterprise-mode','ieee8021x','requires','port auth'),ge('ieee8021x','radius-fed','authenticates-via','RADIUS'),
  ge('wep','iv-attack','broken-by','IV reuse'),ge('wpa','wpa2','replaced-by','AES/CCMP'),ge('wpa2','wpa3','upgraded-to','SAE+stronger'),
  ge('wpa3','sae','uses','Dragonfly'),ge('wpa3','enhanced-open','uses','OWE'),
  ge('psk','sae','replaced-by','offline-safe'),
  ge('peap','eap-tls','weaker-than','cert both sides'),ge('eap-tls','ptk','derives','session key'),
  ge('rogue-ap','evil-twin','compared-to','inside vs outside'),
  ge('disassoc','evil-twin','enables','force reconnect'),
  ge('wps-attack','wep','similar-to','PIN flaw'),
  ge('rfid','rfid-clone','attacked-by','copy badge'),
  ge('bluetooth','bluejacking','attacked-by','spam msg'),ge('bluetooth','bluesnarfing','attacked-by','data theft'),ge('bluetooth','bluebugging','attacked-by','full control'),
  ge('war-drive','wireless-audit','authorized-version','same tools'),
  ge('vpn-conc','remote-vpn','terminates','client tunnels'),ge('vpn-conc','site-vpn','terminates','site tunnels'),
  ge('tunnel-mode','esp','uses','full encap'),ge('transport-mode','esp','uses','payload only'),
  ge('ike','esp','negotiates-for','SA keys'),ge('ike','ah','negotiates-for','SA keys'),
  ge('l2tp','tunnel-mode','uses'),ge('nac','ieee8021x','uses','port control'),
  ge('nac','agent-nac','type-of','with software'),ge('nac','agentless-nac','type-of','no software'),
  ge('ppp','pap','carries','insecure'),ge('ppp','chap','carries','challenge-resp'),
  ge('tacacs','net-diameter','predecessor-of','RADIUS successor'),
  ge('site-survey','heat-map','produces'),ge('wifi-analyzer','site-survey','supports'),
];
const G_REPEL=16000,G_SPRING=0.028,G_IDEAL=120,G_GRAVITY=0.003,G_DAMPING=0.80;
let gNodes=[],gNodeMap={},gGraphInited=false,gGraphActive=false;
let gDragNode=null,gDragOff={},gPanning=false,gPanStart={},gTx={x:0,y:0,k:1};
function gTick(){const ns=gNodes;for(let i=0;i<ns.length;i++){const a=ns[i];if(a.pinned)continue;for(let j=i+1;j<ns.length;j++){const b=ns[j];let dx=b.x-a.x,dy=b.y-a.y;const d2=dx*dx+dy*dy+1,d=Math.sqrt(d2);const f=G_REPEL/d2,fx=f*dx/d,fy=f*dy/d;a.vx-=fx;a.vy-=fy;if(!b.pinned){b.vx+=fx;b.vy+=fy;}}}for(const e of GEDGES){const a=gNodeMap[e.s],b=gNodeMap[e.t];if(!a||!b)continue;const dx=b.x-a.x,dy=b.y-a.y,d=Math.sqrt(dx*dx+dy*dy)+0.001;const f=G_SPRING*(d-G_IDEAL),fx=f*dx/d,fy=f*dy/d;if(!a.pinned){a.vx+=fx;a.vy+=fy;}if(!b.pinned){b.vx-=fx;b.vy-=fy;}}for(const n of ns){if(n.pinned)continue;n.vx+=-n.x*G_GRAVITY;n.vy+=-n.y*G_GRAVITY;n.vx*=G_DAMPING;n.vy*=G_DAMPING;n.x+=n.vx;n.y+=n.vy;}}
function runGraphLayout(steps){gNodes.forEach(n=>{n.pinned=false;n.vx=0;n.vy=0;});for(let i=0;i<steps;i++)gTick();gRender();}
const GESTYLE={member:{color:'#1e3a5f',w:1,dash:'3,7',mk:null},'uses':{color:'#222c44',w:1.5,dash:'',mk:'ga-gray'},'type-of':{color:'#222c44',w:1,dash:'',mk:'ga-gray'},'sends-to':{color:'#1abc9c',w:1.5,dash:'',mk:'ga-teal'},'detects':{color:'#2ecc71',w:1.5,dash:'',mk:'ga-green'},'misses':{color:'#e74c3c',w:1.5,dash:'5,3',mk:'ga-red'},'broken-by':{color:'#e74c3c',w:2,dash:'',mk:'ga-red'},'attacked-by':{color:'#e74c3c',w:1.5,dash:'5,3',mk:'ga-red'},'exploits':{color:'#e74c3c',w:1.5,dash:'5,3',mk:'ga-red'},'replaced-by':{color:'#3498db',w:1.5,dash:'',mk:'ga-blue'},'upgraded-to':{color:'#2ecc71',w:1.5,dash:'',mk:'ga-green'},'requires':{color:'#3498db',w:1,dash:'',mk:'ga-blue'},'uses-dragonfly':{color:'#2ecc71',w:1.5,dash:'',mk:'ga-green'},'enables':{color:'#e74c3c',w:1.5,dash:'',mk:'ga-red'},'terminates':{color:'#2ecc71',w:1.5,dash:'',mk:'ga-green'},'negotiates-for':{color:'#2ecc71',w:1,dash:'',mk:'ga-green'},'contains':{color:'#9b59b6',w:1,dash:'',mk:'ga-gray'},'caught-by':{color:'#9b59b6',w:1.5,dash:'',mk:'ga-gray'},'produces':{color:'#06b6d4',w:1,dash:'',mk:'ga-teal'},'supports':{color:'#06b6d4',w:1,dash:'',mk:'ga-teal'},'weaker-than':{color:'#e67e22',w:1,dash:'4,4',mk:null},'derives':{color:'#2ecc71',w:1.5,dash:'',mk:'ga-green'},'compared-to':{color:'#475569',w:1,dash:'4,4',mk:null},'personal-mode':{color:'#e67e22',w:1,dash:'',mk:'ga-gray'},'enterprise-mode':{color:'#3498db',w:1,dash:'',mk:'ga-blue'},'authenticates-via':{color:'#1abc9c',w:1.5,dash:'',mk:'ga-teal'},'carries':{color:'#222c44',w:1,dash:'',mk:'ga-gray'},'predecessor-of':{color:'#3498db',w:1,dash:'4,4',mk:null},'authorized-version':{color:'#1abc9c',w:1,dash:'4,4',mk:null},};
function gRender(){const svgGe=document.getElementById('ge'),svgGn=document.getElementById('gn');svgGe.innerHTML='';svgGn.innerHTML='';function el(tag,attrs){const e=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);return e;}
for(const e of GEDGES){const a=gNodeMap[e.s],b=gNodeMap[e.t];if(!a||!b)continue;const st=GESTYLE[e.type]||GESTYLE.uses;const dx=b.x-a.x,dy=b.y-a.y,d=Math.sqrt(dx*dx+dy*dy)+0.001;const sr=a.r+2,er=b.r+(st.mk?9:2);const x1=a.x+dx/d*sr,y1=a.y+dy/d*sr,x2=b.x-dx/d*er,y2=b.y-dy/d*er;const line=el('line',{x1,y1,x2,y2,stroke:st.color,'stroke-width':st.w,opacity:e.type==='member'?'0.25':'0.65','data-gs':e.s,'data-gt':e.t});if(st.dash)line.setAttribute('stroke-dasharray',st.dash);if(st.mk)line.setAttribute('marker-end',`url(#${st.mk})`);svgGe.appendChild(line);}
for(const n of gNodes){const isCat=n.id.startsWith('cat-');const g=el('g',{transform:`translate(${n.x.toFixed(1)},${n.y.toFixed(1)})`,cursor:'pointer','data-g-node-id':n.id});const circle=el('circle',{r:n.r,fill:n.color+'22',stroke:n.color,'stroke-width':isCat?'2.5':'1.5'});g.appendChild(circle);const lines=n.label.split('\n');const lh=11,sy=-(lines.length-1)*lh/2;lines.forEach((lbl,i)=>{const t=el('text',{'text-anchor':'middle','dominant-baseline':'middle',y:sy+i*lh,'font-size':n.r>28?'10':'9','font-family':'Segoe UI,system-ui,sans-serif','font-weight':'700',fill:n.color,'pointer-events':'none'});t.textContent=lbl;g.appendChild(t);});g.addEventListener('mouseenter',()=>{circle.setAttribute('fill',n.color+'44');circle.setAttribute('stroke-width','2.5');});g.addEventListener('mouseleave',()=>{if(gDragNode!==n){circle.setAttribute('fill',n.color+'22');circle.setAttribute('stroke-width',isCat?'2.5':'1.5');}});g.addEventListener('mousedown',ev=>{ev.stopPropagation();gDragNode=n;n.pinned=true;const pt=gSvgPt(ev);gDragOff={x:pt.x-n.x,y:pt.y-n.y};});g.addEventListener('click',ev=>{ev.stopPropagation();if(n.nodeId&&NODE_DATA[n.nodeId])openDetail(n.nodeId);});svgGn.appendChild(g);}gApplyTx();if(activeCat)applyGraphFilter(activeCat);}
function gSvgPt(e){const r=document.getElementById('graph-svg').getBoundingClientRect();return{x:(e.clientX-r.left-gTx.x)/gTx.k,y:(e.clientY-r.top-gTx.y)/gTx.k};}
function gApplyTx(){document.getElementById('graph-root').setAttribute('transform',`translate(${gTx.x.toFixed(1)},${gTx.y.toFixed(1)}) scale(${gTx.k.toFixed(4)})`);}
function fitGraph(){if(!gNodes.length)return;const svg=document.getElementById('graph-svg');const{width:W,height:H}=svg.getBoundingClientRect();let mnx=1e9,mxx=-1e9,mny=1e9,mxy=-1e9;gNodes.forEach(n=>{mnx=Math.min(mnx,n.x-n.r);mxx=Math.max(mxx,n.x+n.r);mny=Math.min(mny,n.y-n.r);mxy=Math.max(mxy,n.y+n.r);});const pad=50,k=Math.min((W-pad*2)/(mxx-mnx),(H-pad*2)/(mxy-mny),1.8);gTx.k=k;gTx.x=W/2-(mnx+mxx)/2*k;gTx.y=H/2-(mny+mxy)/2*k;gApplyTx();}
function gSetupInteraction(){const svg=document.getElementById('graph-svg');svg.addEventListener('wheel',e=>{e.preventDefault();const r=svg.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top;const f=e.deltaY<0?1.12:0.89;gTx.x=mx-(mx-gTx.x)*f;gTx.y=my-(my-gTx.y)*f;gTx.k=Math.max(0.12,Math.min(4,gTx.k*f));gApplyTx();},{passive:false});svg.addEventListener('mousedown',e=>{const tgt=e.target;if(tgt===svg||tgt.id==='graph-root'||tgt.id==='ge'||tgt.id==='gn'){gPanning=true;gPanStart={x:e.clientX-gTx.x,y:e.clientY-gTx.y};}});window.addEventListener('mousemove',e=>{if(gDragNode){const pt=gSvgPt(e);gDragNode.x=pt.x-gDragOff.x;gDragNode.y=pt.y-gDragOff.y;gRender();}else if(gPanning){gTx.x=e.clientX-gPanStart.x;gTx.y=e.clientY-gPanStart.y;gApplyTx();}});window.addEventListener('mouseup',()=>{gDragNode=null;gPanning=false;});}
function applyGraphFilter(catId){const cat=CATEGORIES.find(c=>c.id===catId);if(!cat)return;const matchSet=new Set(cat.nodes);document.querySelectorAll('#gn > g[data-g-node-id]').forEach(g=>{const nid=g.dataset.gNodeId,isCat=nid.startsWith('cat-');const nodeId=GNODES.find(n=>n.id===nid)?.nodeId;const vis=isCat||(nodeId&&matchSet.has(nodeId));g.style.opacity=vis?'1':'0.05';g.style.pointerEvents=vis?'auto':'none';});document.querySelectorAll('#ge > line[data-gs][data-gt]').forEach(line=>{const sN=GNODES.find(n=>n.id===line.dataset.gs),tN=GNODES.find(n=>n.id===line.dataset.gt);const sv=!sN||sN.id.startsWith('cat-')||(sN.nodeId&&matchSet.has(sN.nodeId));const tv=!tN||tN.id.startsWith('cat-')||(tN.nodeId&&matchSet.has(tN.nodeId));line.style.opacity=(sv&&tv)?'0.6':'0.04';});}
function clearGraphFilter(){document.querySelectorAll('#gn > g[data-g-node-id]').forEach(g=>{g.style.opacity='';g.style.pointerEvents='';});document.querySelectorAll('#ge > line').forEach(l=>l.style.opacity='');}
function toggleGraphView(){gGraphActive=!gGraphActive;const btn=document.getElementById('btn-graph'),gview=document.getElementById('graph-view'),canvas=document.getElementById('canvas');if(gGraphActive){btn.style.cssText='border-color:var(--teal);color:var(--teal);background:rgba(26,188,156,.1)';gview.classList.add('visible');canvas.style.display='none';if(!gGraphInited){gNodes=GNODES.map(n=>({...n}));gNodeMap={};gNodes.forEach(n=>gNodeMap[n.id]=n);const deg={};gNodes.forEach(n=>deg[n.id]=0);GEDGES.forEach(e=>{if(deg[e.s]!==undefined)deg[e.s]++;if(deg[e.t]!==undefined)deg[e.t]++;});gNodes.forEach(n=>{n.r=n.id.startsWith('cat-')?36:Math.max(18,Math.min(34,18+(deg[n.id]||0)*1.4));});runGraphLayout(300);gSetupInteraction();gGraphInited=true;}setTimeout(fitGraph,60);if(activeCat)applyGraphFilter(activeCat);}else{btn.style.cssText='';gview.classList.remove('visible');canvas.style.display='';}}

/* ═══ ILLUSTRATED MODE ═══ */
let illustratedMode=false;
const GICONS={'cat-ids':'🔍','cat-dec':'🍯','cat-wifi':'📶','cat-survey':'🗺','cat-wpa':'🔒','cat-wpa3':'🛡','cat-eap':'🔐','cat-atk':'⚔','cat-bt':'📲','cat-vpn':'🔒','cat-nac':'🚦','hids':'💻','nids':'📡','sig-ids':'🗂','trend-ids':'📈','zero-day':'0️','aggregator':'🔗','port-mirror':'🪞','port-tap':'🔌','apt':'🎯','honeypot':'🍯','honeynet':'🕸','honeyfile':'📄','honeytoken':'🎟','wlan':'📶','ap':'📡','ssid':'📛','mac-addr':'🏷','mac-filter':'🚫','net-bands':'🌊','wifi-std':'📋','site-survey':'🗺','wifi-analyzer':'🔍','heat-map':'🌡','wireless-footprint':'👣','omni-antenna':'⭕','dir-antenna':'➡','wep':'⚠','wpa':'⚠','wpa2':'🔒','psk':'🔑','open-mode':'🔓','enterprise-mode':'🏛','shared-secret':'🤝','wpa3':'🛡','sae':'🐉','enhanced-open':'🌐','wpa3-enterprise':'🏰','peap':'🔐','eap-fast':'⚡','eap-tls':'🏆','eap-ttls':'🔐','ptk':'🗝','ieee8021x':'🚦','radius-fed':'🌐','captive-portal':'🌐','disassoc':'💥','wps-attack':'📌','rogue-ap':'👿','evil-twin':'😈','jamming':'📻','iv-attack':'🔢','nfc-attack':'📳','rfid':'📡','rfid-clone':'📋','sniffing':'👃','data-exfil':'📤','ddos':'🌊','wireless-replay':'🔄','bluetooth':'📲','bluejacking':'💬','bluesnarfing':'🕵','bluebugging':'🐛','war-drive':'🚗','war-fly':'🚁','wireless-audit':'✅','vpn-conc':'🔀','remote-vpn':'🏠','site-vpn':'🏢','always-on-vpn':'🔁','split-tunnel':'✂','full-tunnel':'🔒','html5-vpn':'🌐','tunnel-mode':'🚇','transport-mode':'📦','esp':'🔐','ah':'✍','ike':'🤝','sstp':'🌐','l2tp':'🔗','nac':'🚦','agent-nac':'👁','agentless-nac':'🌐','pap':'⚠','ppp':'🔗','chap':'❓','tacacs':'🏛','net-diameter':'📐',};
const GEDGE_DESC={'nids->port-mirror':'NIDS receives\ntraffic via SPAN','nids->port-tap':'Hardware tap\nprovides full capture','sig-ids->zero-day':'Signature IDS\nbLind to zero-days','trend-ids->zero-day':'Detects via\nbehavior change','nids->aggregator':'Sends alerts\nto aggregator','hids->aggregator':'Sends host\nevents to aggregator','apt->zero-day':'APTs exploit\nunknown vulnerabilities','apt->honeypot':'Honeypots catch\nAPTs early','honeynet->honeypot':'Honeynet is\nmultiple honeypots','wpa2->psk':'PSK mode uses\nshared passphrase','wpa2->enterprise-mode':'Enterprise uses\n802.1X/RADIUS','enterprise-mode->ieee8021x':'Enterprise requires\nport-based auth','ieee8021x->radius-fed':'802.1X authenticates\nvia RADIUS','wep->iv-attack':'WEP broken by\nIV reuse attack','wpa->wpa2':'WPA/TKIP replaced\nby WPA2/AES','wpa2->wpa3':'WPA3 upgrades\nSAE + stronger','wpa3->sae':'SAE replaces\nPSK handshake','wpa3->enhanced-open':'OWE encrypts\nopen networks','psk->sae':'SAE makes PSK\nresistant to offline attack','peap->eap-tls':'EAP-TLS stronger:\nrequires client cert','eap-tls->ptk':'Session PTK\nderived after auth','rogue-ap->evil-twin':'Both AP attacks\nbut different locations','disassoc->evil-twin':'Deauth forces\nreconnect to evil twin','bluetooth->bluejacking':'Bluejacking sends\nunsolicited messages','bluetooth->bluesnarfing':'Bluesnarfing steals\ndata silently','bluetooth->bluebugging':'Bluebugging gives\nfull device control','war-drive->wireless-audit':'Audit = authorized\nwar driving','vpn-conc->remote-vpn':'Concentrator handles\nclient VPN tunnels','vpn-conc->site-vpn':'Concentrator handles\nsite-to-site tunnels','tunnel-mode->esp':'Tunnel mode uses\nESP for encryption','transport-mode->esp':'Transport mode uses\nESP for payload','ike->esp':'IKE negotiates\nESP security assoc','l2tp->tunnel-mode':'L2TP creates\nthe tunnel','nac->ieee8021x':'NAC uses 802.1X\nfor port control','nac->agent-nac':'Agent = software\non endpoint','nac->agentless-nac':'Agentless = network\nside scanning','ppp->pap':'PPP carries\ninsecure PAP','ppp->chap':'PPP carries\nCHAP challenge','site-survey->heat-map':'Survey produces\nRF heat map','wifi-analyzer->site-survey':'Analyzer supports\nsite surveys',};
function getEdgeDesc(e){return GEDGE_DESC[`${e.s}->${e.t}`]||null;}
const _origGRender=gRender;
gRender=function(){if(!illustratedMode){_origGRender();return;}const svgGe=document.getElementById('ge'),svgGn=document.getElementById('gn');svgGe.innerHTML='';svgGn.innerHTML='';function el(tag,attrs){const e=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);return e;}
for(const e of GEDGES){const a=gNodeMap[e.s],b=gNodeMap[e.t];if(!a||!b)continue;const st=GESTYLE[e.type]||GESTYLE.uses;const dx=b.x-a.x,dy=b.y-a.y,d=Math.sqrt(dx*dx+dy*dy)+0.001;const sr=38,er=38+(st.mk?9:2);const x1=a.x+dx/d*sr,y1=a.y+dy/d*sr,x2=b.x-dx/d*er,y2=b.y-dy/d*er;const line=el('line',{x1,y1,x2,y2,stroke:st.color,'stroke-width':st.w,opacity:e.type==='member'?'0.2':'0.7','data-gs':e.s,'data-gt':e.t});if(st.dash)line.setAttribute('stroke-dasharray',st.dash);if(st.mk)line.setAttribute('marker-end',`url(#${st.mk})`);svgGe.appendChild(line);const desc=getEdgeDesc(e);if(desc&&e.type!=='member'){const mx=(a.x+b.x)/2,my=(a.y+b.y)/2;const lines=desc.split('\n');const bw=78,bh=lines.length*10+6;svgGe.appendChild(el('rect',{x:mx-bw/2,y:my-bh/2,width:bw,height:bh,rx:'3',fill:'#07090f',stroke:st.color,'stroke-width':'0.5',opacity:'0.92'}));lines.forEach((ln,i)=>{const t=el('text',{x:mx,y:my-(lines.length-1)*5+i*10,'text-anchor':'middle','dominant-baseline':'middle','font-size':'7.5','font-family':'Segoe UI,system-ui,sans-serif','font-weight':'600',fill:st.color,'pointer-events':'none'});t.textContent=ln;svgGe.appendChild(t);});}}
const NW=72,NH=58;for(const n of gNodes){const isCat=n.id.startsWith('cat-');const g=el('g',{transform:`translate(${n.x.toFixed(1)},${n.y.toFixed(1)})`,cursor:'pointer','data-g-node-id':n.id});const rect=el('rect',{x:-NW/2,y:-NH/2,width:NW,height:NH,rx:'8',fill:n.color+'18',stroke:n.color,'stroke-width':isCat?'2.5':'1.5'});g.appendChild(rect);const icon=el('text',{y:'-7','text-anchor':'middle','dominant-baseline':'middle','font-size':isCat?'20':'16','pointer-events':'none'});icon.textContent=GICONS[n.id]||'●';g.appendChild(icon);const lbl=el('text',{y:'13','text-anchor':'middle','dominant-baseline':'middle','font-size':'7.5','font-family':'Segoe UI,system-ui,sans-serif','font-weight':'700',fill:n.color,'pointer-events':'none'});lbl.textContent=n.label.replace(/\n/g,' ');g.appendChild(lbl);g.addEventListener('mouseenter',()=>rect.setAttribute('fill',n.color+'35'));g.addEventListener('mouseleave',()=>{if(gDragNode!==n)rect.setAttribute('fill',n.color+'18');});g.addEventListener('mousedown',ev=>{ev.stopPropagation();gDragNode=n;n.pinned=true;const pt=gSvgPt(ev);gDragOff={x:pt.x-n.x,y:pt.y-n.y};});g.addEventListener('click',ev=>{ev.stopPropagation();if(n.nodeId&&NODE_DATA[n.nodeId])openDetail(n.nodeId);});svgGn.appendChild(g);}gApplyTx();if(activeCat)applyGraphFilter(activeCat);};
function toggleIllustrated(){if(!gGraphActive)toggleGraphView();illustratedMode=!illustratedMode;const btn=document.getElementById('btn-illustrated');btn.style.cssText=illustratedMode?'border-color:var(--purple);color:var(--purple);background:rgba(155,89,182,.12)':'';btn.textContent=illustratedMode?'🖼 Bubble View':'🖼 Illustrated';gRender();}

let studyMode=false;
function toggleStudyMode(){
  studyMode=!studyMode;const btn=document.getElementById('btn-study');
  document.querySelectorAll('.node-label,.node-sub').forEach(el=>el.style.opacity=studyMode?'0':'');
  btn.style.cssText=studyMode?'border-color:var(--teal);color:var(--teal);background:rgba(26,188,156,.1)':'';
  btn.textContent=studyMode?'👁 Labels Hidden':'👁 Study Mode';
}
